### ISSUE TITLE
Remap App Shortcuts

### ISSUE THREAD

**Issue by TheMrMarcks** [djlastnight/KeyboardSplitterXbox#105]
I was searching an alternative to github.com/mikew/xarcade-xinput (i wrote an issue github.com/mikew/xarcade-xinput/issues/40 but no answers) and i found this program, its working great, but the problem its that if i want to use the control button as another button of the pad that wont cause problems while playing?? there is a way to change the shorcuts that the app uses to block-keyboard/block-mouse/start/stop?? a way to start it via command line would be usefull too, maybe to use it on arcade machines with ipac boards

**Comment by djlastnight** [comment]
Similar to #61. Closing this.

**Comment by pragunvohra** [comment]
I posted an update on #61 with an AHK script that works as a command line. It isn't generic enough for everyone but should give anyone an idea how to change it for their needs. Providing freely and as-is.
