### ISSUE TITLE
Causes Keyboard to not work even after uninstall?

### ISSUE THREAD

**Issue by adamllryan** [djlastnight/KeyboardSplitterXbox#106]
Installed because I was 2 controllers short, didn't work, so I gave up and deleted the program. Now my keyboard will stop working once it disconnects and reconnects. Something is blocking the keyboard input, because I know it still works and it sometimes disables it shortly after login. How to fix?

**Comment by djlastnight** [comment]
Uninstall the built in drivers

**Comment by Yintel12138** [comment]
which driver I should uninstall？thank U

**Comment by djlastnight** [comment]
Hi, if you have access to the app ui, go to drivers file menu and you will see the option for uninstall, otherwise, please go to this repo's readme

**Comment by Yintel12138** [comment]
> 

thank U, It makes my keyboard work!
