### ISSUE TITLE
VirtualXboxNative.dll

### ISSUE THREAD

**Issue by edergames29** [djlastnight/KeyboardSplitterXbox#110]
**Eu já tenho o drive do xbox 360 instalado.**
B] - Application started from C:\Users\ederg\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Sun] 24 Oct, 2021 [19:36:15] [Mem: 8 MB] - User has write permissions: True
[Sun] 24 Oct, 2021 [19:36:16] [Mem: 8 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sun] 24 Oct, 2021 [19:36:16] [Mem: 8 MB] - OS version: Windows 10 x64 build 19043 
[Sun] 24 Oct, 2021 [19:36:16] [Mem: 8 MB] - Setting environment
[Sun] 24 Oct, 2021 [19:36:16] [Mem: 9 MB] - Loading interception 1.00
[Sun] 24 Oct, 2021 [19:36:16] [Mem: 9 MB] - Loading VirtualXboxNative 2.2.0.0
[Sun] 24 Oct, 2021 [19:36:19] [Mem: 12 MB] - Loading SplitterCore 2.2.0.0
[Sun] 24 Oct, 2021 [19:36:19] [Mem: 12 MB] - Loading Interceptor 2.2.0.0
[Sun] 24 Oct, 2021 [19:36:19] [Mem: 12 MB] - Loading VirtualXbox 2.2.0.0
[Sun] 24 Oct, 2021 [19:36:21] [Mem: 12 MB] - Interception driver state: not installed
[Sun] 24 Oct, 2021 [19:36:21] [Mem: 12 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sun] 24 Oct, 2021 [19:36:21] [Mem: 12 MB] - System.DllNotFoundException: Não é possível carregar a DLL 'VirtualXboxNative.dll': Não foi possível encontrar o módulo especificado. (Exceção de HRESULT: 0x8007007E)
   em VirtualXbox.NativeMethods.VBusExists()
   em KeyboardSplitter.App.ReportDriversState()
   em KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   em System.Windows.Application.OnStartup(StartupEventArgs e)
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
Install the prerequisites
