### ISSUE TITLE
keyboard splitter not working

### ISSUE THREAD

**Issue by NICO090878656** [djlastnight/KeyboardSplitterXbox#114]
When me and my cousin play ninja storm 4 using keyboard splitter it works but when he press "w" which is move forward button for him, i moved also even though we have entirely different controls and also he uses laptop keypad and i used real keyboard. Is there any way to fix this problem?

**Comment by djlastnight** [comment]
please connect the keyboards, press w on the first, then w on the second - this should be done with input monitor open.
Send me a screenshot of the monitor
