### ISSUE TITLE
keyboard splitter doesn't work

### ISSUE THREAD

**Issue by benekj** [djlastnight/KeyboardSplitterXbox#116]
i'm trying to play the binding of isaac with someone using steam remote and i'm trying to use keyboard splitter but when i set up everything turn on the game everything works steam remote play detects that i "have" a controller the game also says that the controller is on but when i try to play it only detects my keyboard i can't switch to the controller bc it switches back to my keyboard. when i try to test the controller it shows everything but doesn't show the actual inputs like nothing is set 
why is it happening what's wrong how do i fix it

**Comment by djlastnight** [comment]
idk how steam remote works. please use the software the way you should use it. this includes mine and the steam's too. any exceptional cases you try on own risk.
