### ISSUE TITLE
Changing the LCtrl button of blocking keyboard to different keybind 

### ISSUE THREAD

**Issue by internumentity** [djlastnight/KeyboardSplitterXbox#117]
hello , so i have been playing a game and i noticed that as i press the LCtrl key alot of times , it blocks the keyboard. And im used to play with the LCtrl keybind for long time. please help on how to change the LCtrl to a different key on Splitter.
Best Regards

**Comment by djlastnight** [comment]
Are you the guy from youtube, to whom I sent special build?

**Comment by djlastnight** [comment]
You can use the no ctrl keys version (i.e Ctrl keys won't check the checkboxes) - USE ON OWN RISK!
[KeyboardSplitter_no_ctrl_hotkeys.zip](https://github.com/djlastnight/KeyboardSplitterXbox/files/7909022/KeyboardSplitter_no_ctrl_hotkeys.zip)
