### ISSUE TITLE
i cant Open keyboard splitter any help??

### ISSUE THREAD

**Issue by iClapp** [djlastnight/KeyboardSplitterXbox#121]
hey i cant open the keyboard splitter can u please help? is there something im missing, i just downloaded it and it came like this

![keyboard splitter crash log](https://user-images.githubusercontent.com/97369645/148664979-e51d7c8a-31e7-4bb8-83e6-c2c7fb0e5baa.PNG)
![keyboard splitter software](https://user-images.githubusercontent.com/97369645/148664980-c6893d6d-7d76-48f6-ac87-4a3f7005e013.PNG)
![logg](https://user-images.githubusercontent.com/97369645/148668236-9c335711-f32b-40ac-9d74-eb2663a14990.PNG)

**Comment by iClapp** [comment]
@djlastnight

**Comment by djlastnight** [comment]
well it seems it fails to install the drivers. can u please try older version

**Comment by sanketdhole00** [comment]
@djlastnight  Can u help me with this error?
![splitterlog_error](https://user-images.githubusercontent.com/70258831/158011544-088a6997-3bde-4a5b-b9bf-3aab211887e0.png)
any suggestions?

**Comment by djlastnight** [comment]
Install all this https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites
Reopen if it still does not work.
