### ISSUE TITLE
KeyBoard Splitter Error: no input devices were detected!

### ISSUE THREAD

**Issue by Helton-Rubens** [djlastnight/KeyboardSplitterXbox#125]
Hi, can you help me pls?

![image](https://user-images.githubusercontent.com/81119434/165193250-517f71d3-3b43-43b4-bc8f-65222dbb2ba7.png)

![image](https://user-images.githubusercontent.com/81119434/165193344-74d94089-ce9b-4728-b1fa-10043c7a3bc8.png)

**So I did what you asked in this video:**
https://www.youtube.com/channel/UCAK3R_8Qq1Z8bKXX5nh8Tyg

**But that didn't work:**

![image](https://user-images.githubusercontent.com/81119434/165193596-a8bc446f-a0eb-46f2-93ec-11ac22b15b92.png)

**_I also reinstalled the drivers but it didn't solve the problems_**

**Comment by Klefo0** [comment]
I have got this error recently, very annoying

**Comment by djlastnight** [comment]
ah too late for this reply, but anyways I wrote GUI for uninstalling keyboard driver, you can try it [Interception GUI Uninstaller](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true)

**Comment by SorelS52** [comment]
hi djlastnight the interception GUI Uninstaller actualy don't work for me how can I do this?

**Comment by djlastnight** [comment]
Try the method above then in windows safe mode. I did not tested the interception gui uninstaller at safe mode also.
