### ISSUE TITLE
Icons not loading 

### ISSUE THREAD

**Issue by MaguirePool** [djlastnight/KeyboardSplitterXbox#127]
Hi so i downloaded this and all stuff and uninstall the scp thing blah blah i did all then this one this still comes like this

![image](https://user-images.githubusercontent.com/88889733/165868328-282bf7fd-0968-4a09-8ffb-3e9f37507b14.png)

![image](https://user-images.githubusercontent.com/88889733/165868351-ab3b7182-d46e-451f-af47-ad869f72b815.png)

how to fix

**Comment by djlastnight** [comment]
Hi. There are no xinput controller currently found on your system.
You have 2 options (might even mix them)
1. Connect a real gamepad and it will appear
2. Start the emulation, then open this window
