### ISSUE TITLE
After i installed the drivers my mouse stopped working out of nowhere

### ISSUE THREAD

**Issue by Binguslovesyou** [djlastnight/KeyboardSplitterXbox#129]
After i intalled the drivers my mouse stopped working out of nowhere, it says the drivers are corrupted or missing. I already tried uninstalling and installing it again but its not working, how do i fix this?
![image](https://user-images.githubusercontent.com/104937120/166810935-f71cf8cb-4d1c-434f-b26d-ff4138c8dc45.png)

**Comment by Binguslovesyou** [comment]
This is really annoying, please help

**Comment by ardiprasetiyo** [comment]
Any updates?

**Comment by djlastnight** [comment]
Sorry guys, I did not update this app recently, probably windows has too much changes and the drivers does not work as they should anymore.
