### ISSUE TITLE
keyboard and mouse got blocked

### ISSUE THREAD

**Issue by xantana1** [djlastnight/KeyboardSplitterXbox#130]
after downloading splitter, i had to restart my pc, just when my pc restarted i got my mouse and keyboard blocked, idk what to do, please give me some advices how to turn off program or what can i do

**Comment by JerellDR** [comment]
I believe I have a similar issue although with the mouse. The program blocks my mouse even when the block options was turned off. What I had to do was press alt to get to the menu and click exit. Once the program is closed you should have access to your mouse and keyboard again.   Any way to troubleshoot why this is happening?

**Comment by djlastnight** [comment]
Well I guess the drivers does not work as they should anymore - see their author repo issues too https://github.com/oblitum/Interception/issues
