### ISSUE TITLE
[REQUEST] Possibility for moving axis incrementally

### ISSUE THREAD

**Issue by viictorgomes** [djlastnight/KeyboardSplitterXbox#131]
I would like to ask for a possibility for moving axis incrementally, current state of the program when you press trigger or a button to move any stick, it instantly goes from 0% to 100% and im asking for a feature that allows that value going slower, incrementally from 0% to 100% smoothly in a way that allows to be adjusted how long it takes

Thanks

**Comment by djlastnight** [comment]
Hey, cool request, but honestly I believe this will be very hard to achieve (without causing other issues), since the app does not work this way. It has a list of static predefined xbox functions like Axis_X_Min, Axis_X_Max, etc..

**Comment by djlastnight** [comment]
If you wish you can try this one https://github.com/djlastnight/KeyboardSplitterXbox#custom-axes-range-0-100
It's not exactly what you wish, since it is not time based, but at least the axis won't always go to 100% all the time.
