### ISSUE TITLE
both keyboards control the game

### ISSUE THREAD

**Issue by githubcool123** [djlastnight/KeyboardSplitterXbox#134]
i tried using this on a game and
lets say that if i press A to make my character go left.
it's the same on the other keyboard, if they press A their character also goes left.
but, when the second keyboard presses A, my character ALSO moves left, even though i'm not pressing anything
and when the first keyboard press A, only my character moves

**Comment by DaLLuZZ** [comment]
Is it possible if you could try any other presets?

**Comment by djlastnight** [comment]
I believe the OP needs to read the FAQ, closing this :)
