### ISSUE TITLE
Another REQUEST for Command Line

### ISSUE THREAD

**Issue by phantomfsoc** [djlastnight/KeyboardSplitterXbox#135]
Hi,
I know this as been asked a few years ago but having the option to run Game Splitter from a command line would be a "Game Changer" (see what I did there?)
I too like many run an Arcade cab that relies on Keyboard controls and using Game Splitter has opened up my cab to a bunch of new games but using the GUI takes away from the experience and not user friendly on on a cab.
I saw the Auto Key script that was posted but it doesn't seem to work for me.

Thanks for all your work

**Comment by djlastnight** [comment]
Yes yes, I fully agree, but simply I don't have time enough to push this project forward.

**Comment by djlastnight** [comment]
@phantomfsoc, please try this release. I've just added CLI support [release 2.3](https://github.com/djlastnight/KeyboardSplitterXbox/releases/2.3.0.0)

[How To Use CLI](https://github.com/djlastnight/KeyboardSplitterXbox#command-line-interface-cli)
