### ISSUE TITLE
Let Me Change Global Shortcuts from Left/Right Controll to something else

### ISSUE THREAD

**Issue by xpdatabase11** [djlastnight/KeyboardSplitterXbox#139]
If a game needs me to press Left or Right controll repeadatelly then it keeps blocking and unblocking the mice or keyboard. If i could change this to a different key like for example home button and end. That would better.

**Comment by JanMiddelkoop** [comment]
I would love to be able to change these keys, because I find myself inadvertently turning off keyboard block during games. Assinging the shortcuts to different keys might not even be necessary; if I could just disable these shortcuts that'd be splendid as well.

**Comment by djlastnight** [comment]
Sorry guys, but those are reserved for the app and this is not accidental.
