### ISSUE TITLE
Keyboard splitter not working in DBC 17 after few minutes

### ISSUE THREAD

**Issue by therealtechpatel** [djlastnight/KeyboardSplitterXbox#14]
I have the latest version of keyboard splitter and when I use it in DB17 after a few minutes the game doesn't recognise the "controller"(keyboard splitter) and its controls don't work. I have used Keyboard splitter in Ashes cricket and have had no problems like this how can I fix this in DBC17

**Comment by djlastnight** [comment]
This is a game related. You have to buy the original one.
