### ISSUE TITLE
Keyoard splitter does not recognize any input devices

### ISSUE THREAD

**Issue by SALAYH** [djlastnight/KeyboardSplitterXbox#140]
It was working just fine but then keyboards stopped working at all. Then i turned off the pc by power button. After booting, i removed drivers and then installed them again. Now. it says no input devices found. I cannot uninstall the drivers as program does not open
![Capture](https://user-images.githubusercontent.com/111347033/184838442-fd5fae2c-8b82-4ed4-8565-7c789716db22.PNG)
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/9349215/splitter_log.txt)

**Comment by HZLYB** [comment]
是否解决  

![屏幕截图 2022-12-23 205821](https://user-images.githubusercontent.com/78646441/209340044-339067fe-3ab1-463f-a6e4-f115a5141416.png)
(url)

**Comment by HuzaifaLk** [comment]
same error showing @djlastnight Please help

**Comment by djlastnight** [comment]
Probably the interception driver is broken after window update. Try the  [Interception GUI Uninstaller](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true) (run Uninstall.exe)

**Comment by TheThreatner** [comment]
@SALAYH  did this worked for you?
