### ISSUE TITLE
Lag Issues

### ISSUE THREAD

**Issue by HearinStormborn** [djlastnight/KeyboardSplitterXbox#141]
Hi! First of all, thank you for creating such a wonderful thing.

I am having an issue whenever I use it. After using it after a couple minutes the controls start to slow down and after about 30 minutes the controls start to get locked. For example if, I was pressing left and decide to press right, it would still give the input of me pressing left. Tried both blocking and unblocking the keyboards but it just doesn't make much of a difference. Is this related to my hardware? The cpu doesn't seem to be having a bad time.
Also as a side note. Writing with it is practically impossible as the letters I use for controls become stuck and press a couple times in a row.

**Comment by djlastnight** [comment]
Hey, idk what might cause this performance issue, but you can try to run the app via CLI https://github.com/djlastnight/KeyboardSplitterXbox#command-line-interface-cli
