### ISSUE TITLE
Controller plug in failed

### ISSUE THREAD

**Issue by Tieruu** [djlastnight/KeyboardSplitterXbox#142]
Hello cant run the program correctly. Here's the log. 
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 18 MB] - Application started from C:\Users\basil\Downloads\Nouveau dossier\KeyboardSplitterXbox-master\KeyboardSplitter\bin\Release\KeyboardSplitter.exe
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - User has write permissions: True
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - OS version: Windows 10 x64 build 19044 
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - Setting environment
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - Loading interception 1.00
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 25 MB] - Loading SplitterCore 2.2.0.0
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 25 MB] - Interception driver state: installed
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 26 MB] - ScpVBus driver state: installed
[Mon] 29 Aug, 2022 [13:58:29] [Mem: 26 MB] - Xbox accessories driver state: installed
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 37 MB] - Loading XinputWrapper 2.2.0.0
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 37 MB] - Trying to apply app [settings]
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - [settings] 'Mouse move dead zone' set to: 1
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - [settings] 'Display emulation information' set to: True
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - [settings] 'Starting virtual controller user index' set to: 1
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - Main window loaded
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 38 MB] - Creating splitter with 1 slots 
[Mon] 29 Aug, 2022 [13:58:30] [Mem: 39 MB] - Creating input manager
[Mon] 29 Aug, 2022 [13:58:34] [Mem: 52 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!

I dont know what to do please help me. thx for your time.
Tieru

**Comment by mccarey88** [comment]
I have the same issue, here is the log. Maybe it will help

[Tue] 30 Aug, 2022 [00:52:05] [Mem: 18 MB] - Application started from D:\Programy\Keyboard splitter\KeyboardSplitter.exe
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 18 MB] - User has write permissions: True
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 19 MB] - OS version: Windows 10 x64 build 19044 
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 19 MB] - Setting environment
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 19 MB] - Loading interception 1.00
[Tue] 30 Aug, 2022 [00:52:05] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 25 MB] - Interception driver state: installed
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 25 MB] - ScpVBus driver state: installed
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 26 MB] - Xbox accessories driver state: installed
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - Loading XinputWrapper 2.2.0.0
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - Trying to apply app [settings]
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - [settings] 'Mouse move dead zone' set to: 1
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - [settings] 'Display emulation information' set to: True
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - [settings] 'Starting virtual controller user index' set to: 1
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 44 MB] - Main window loaded
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 45 MB] - Creating splitter with 4 slots 
[Tue] 30 Aug, 2022 [00:52:06] [Mem: 45 MB] - Creating input manager
[Tue] 30 Aug, 2022 [00:53:01] [Mem: 73 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!
[Tue] 30 Aug, 2022 [00:53:08] [Mem: 74 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!
[Tue] 30 Aug, 2022 [00:53:10] [Mem: 75 MB] - Application is about to close. Checking for unsaved presets...
[Tue] 30 Aug, 2022 [00:53:11] [Mem: 76 MB] - Saving game data
[Tue] 30 Aug, 2022 [00:53:11] [Mem: 76 MB] - Main window disposed
[Tue] 30 Aug, 2022 [00:53:11] [Mem: 76 MB] - Settings successfully saved to splitter_settings.xml
[Tue] 30 Aug, 2022 [00:53:11] [Mem: 76 MB] - Application exited with code: 0

**Comment by djlastnight** [comment]
Read this https://github.com/djlastnight/KeyboardSplitterXbox#scp-virtual-bus-version-mismatch
