### ISSUE TITLE
Keyboard Splitter does not open, help me to solve this please developer (; _ ;)

### ISSUE THREAD

**Issue by Himiko16** [djlastnight/KeyboardSplitterXbox#143]
djlastnigth I'm BR, I'm using the translator to let you know this problem, please help me solve it urgently
Every time I open the application an error appears and I didn't find a solution to the problem, I don't know what to do to solve it and it was looking for that I found it, I'm very happy to find the developer and I would be even happier if you can help me :)
I will add the splitter_log file and the error photo when opening the application.
![djlastnight's Gaming Keyboard Splitter v2 2 0 0 30_08_2022 10_41_15](https://user-images.githubusercontent.com/112494204/187465565-db6cafc5-7fec-482a-8ee6-3b22d7cf9afc.png)
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/9453761/splitter_log.txt)

**Comment by 8fn** [comment]
same, lmfao!

**Comment by vaderag** [comment]
Same issue, but you just need to follow the prerequisites: https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites
