### ISSUE TITLE
Wireless Mouse / Keyboard via unified received stop when Keyboard Splitter is open

### ISSUE THREAD

**Issue by vaderag** [djlastnight/KeyboardSplitterXbox#146]
When I open the app, the Wireless Keyboard (with trackpad) and a wireless mouse both stop functioning entirely
I have another mouse/keyboard (an encoder from my arcade controls) which does function

No inputs are detected by the app or anything else from the other devices - they are essentially dead. 
Anyone aware of a workaround for this issue?

**Comment by tprochazka** [comment]
I have probably the same issue. I thought that whole windows just freeze after opening the app, but since I have both the mouse and keyboard from Logitech with the unified receiver it is probably this issue.

**Comment by en-ashay** [comment]
same I too have logitech bluetooth mouse and keyboard, had to restart pc to make the mouse work

**Comment by djlastnight** [comment]
Probably those devices uses 3rd party drivers, which are not compatible with the interception driver, which KS uses.

**Comment by Julzyy** [comment]
Has anyone found a fix for this? I have the logitech g915 tkl wireless keyboard and it just wont register on the splitter no matter what i try. I'm also running the g502 wireless mouse which is working fine.

**Comment by djlastnight** [comment]
@Julzyy does this keyboard comes with some drivers. If so can they be uninstalled (for test purposes)
