### ISSUE TITLE
Virtual Keyboard from Parsec not being detected.

### ISSUE THREAD

**Issue by TaiTair** [djlastnight/KeyboardSplitterXbox#147]
Hi,

When I go to select a keyboard I see keyboard_01-10 - none of them work. If I try to use auto-detect it doesn't detect anything.
This is essentially using a "virtual keyboard" through parsec.

Edit: Input monitor doesn't show any keys pressed either.
Edit2: Seems to be a parsec issue since I can't get reWASD or virtual controller to recognize my keyboard either.

Any advice to get it to detect virtual inputs?

**Comment by djlastnight** [comment]
The app works with the windows virtual (on-screen) keyboard. I didn't test any other virtual ones, so I guess they won't work. If you can research if they uses raw input, I may try to add support for them
