### ISSUE TITLE
unexpected app crash

### ISSUE THREAD

**Issue by BlackHawk371** [djlastnight/KeyboardSplitterXbox#148]
un expected app crash, Kindly help me 
![kb](https://user-images.githubusercontent.com/66234727/209820249-540babcd-a8e0-46c9-bd50-9170fe7fa94c.PNG)

**Comment by djlastnight** [comment]
Try to enable WMI on your system.
Run the `services.msc` and make sure the `Windows Management Instrumention` service is running and its start type is set to `Automatic`
