### ISSUE TITLE
Mouse to Right Stick won't move diagonally

### ISSUE THREAD

**Issue by LuaTheRabbit** [djlastnight/KeyboardSplitterXbox#149]
I have the mouse  connected to the right stick with the inputs and I can move it left, right, up, and down easily with no problems but once I try to move diagonally it bounces between the left and up inputs for top left, right and up for top righty and so on, and that makes the screen constantly jitter. If anyone could help me with this problem I'd very much appreciate it. Everything else works perfectly so.

**Comment by djlastnight** [comment]
Can you try to not use Min/Max of the axis but let say -70% to +70% and see if it works better
https://github.com/djlastnight/KeyboardSplitterXbox#custom-axes-range-from--100-to-100
