### ISSUE TITLE
Cannot delete a preset

### ISSUE THREAD

**Issue by Rex000** [djlastnight/KeyboardSplitterXbox#15]
I'm using the latest v2.0.0.3. When I add/import a preset then exit KS, it prompts me to save, which it actually does. But when I delete a preset then exit KS, there aren't any prompts to save. Then when I start KS again, the previously deleted preset comes back again. Upon investigation, it appears that when I delete a preset and exit KS, the "splitter_presets.xml" file is not updated, which is actually causing this issue. 

I tired the previous version of KS too, and it's the same. Also tried to run KS as admin and disable antivirus completely, but no dice.

I'd appreciate your help. Thanks.

**Comment by djlastnight** [comment]
Issue confirmed. I will fix it now
