### ISSUE TITLE
how to fully uninstall keyboard splitter 

### ISSUE THREAD

**Issue by BBk1999** [djlastnight/KeyboardSplitterXbox#152]
any help i need to delete keyboard splitter coz all my games are crashing i deleted everything related to keyboard splitter and still my games crashing

**Comment by imerso** [comment]
It should have an uninstaller. This is very bad practice not to provide users a way to uninstall a software and its drivers.

I got the same problem, and did the following to uninstall KeyboardSplitter driver:

1 - Open a PowerShell as admin (WinKey+R, type POWERSHELL, then press SHIT+CONTROL+ENTER for it to open as admin)

2 - Inside the above PowerShell, enable scripts execution:

`set-executionpolicy remotesigned
`
3 - Open notepad and paste this script there:

```
# Taken from https://stackoverflow.com/a/41784300
# Initializing parameters (modify the Output folder by changing the $TargetDirectory define in the first line)
$TargetDirectory = "C:\temp\DriversINFTest\"
$hostname = $ENV:COMPUTERNAME
# Get Third Party drivers used, that are not provided by Microsoft and presumably included in the OS
$drivers = Get-WmiObject Win32_PNPSignedDriver | where {$_.DriverProviderName -ne "Microsoft"}
# Initialize the list of detected driver packages as an array
$DriverFolders = @()
foreach ($d in $drivers) {
	# We initialize the list of driver files for each driver
	$DriverFiles = @()
	# For each driver instance from WMI class Win32_PNPSignedDriver, we compose the related WMI object name from the other WMI driver class, Win32_PNPSignedDriverCIMDataFile
	$ModifiedDeviceID = $d.DeviceID -replace "\\", "\\"
	$Antecedent = "\\" + $hostname + "\ROOT\cimv2:Win32_PNPSignedDriver.DeviceID=""$ModifiedDeviceID"""
	# Get all related driver files for each driver listed in WMI class Win32_PNPSignedDriver
	$DriverFiles += Get-WmiObject Win32_PNPSignedDriverCIMDataFile | where {$_.Antecedent -eq $Antecedent}
	if ($DriverFiles -ne $null) {
		foreach ($i in $DriverFiles) {
			# We elliminate double backslashes from the file paths
			$path = $i.Dependent.Split("=")[1] -replace '\\\\', '\'
			# We elliminate the trailing and ending quotes from the file paths
			$path2 = $path.Substring(1,$path.Length-2)
			# On the first pass, we only process the INF files as there is a very low chance of existing more than one driver package on the same machine, with the same INF file legth
			if ($path2.Split("\\")[$path2.Split("\\").Length-1].split(".")[1] -eq "inf") {
				# We get the file attributes for each INF file
				$CurrentDeviceID = $d.DeviceID
				Write-Host "Current Device ID is $CurrentDeviceID"
				$filedetails = $i.Dependent
				Write-Host "Current inf file is $filedetails"
				$where = $filedetails.split("=")[1]
				$query = "select * from CIM_DataFile where Name=$where"
				$InstallDate = Get-WmiObject -Namespace "ROOT\CIMV2" -Query $query
				$ReadableDate = $InstallDate.ConvertToDateTime($InstallDate.InstallDate)
				Write-Host "Installation date is:"
				$ReadableDate
				} # End of if ($path2.Split("\\")[$path2.Split("\\").Length-1].split(".")[1] -eq "inf")
			} # End of foreach ($i in $DriverFiles)
		} # End of if ($DriverFiles -ne $null)
} # End of foreach ($d in $drivers)
```

The above script, when executed, will list installed drivers with their dates. You must know when you installed KeyboardSplitter. By the date you will find which .inf file is related to KeyboardSplitter.

4 - From the list shown, find the driver which was installed in the day and time you installed KeyboardSplitter. There you will also find the name of the .inf file used for that. Mine was "oem71.inf", for instance. Yours will most probably be a different name.

If you don't know the date you installed KeyboardSplitter, you can still find it -- I took no note but I strongly believe it is related to the file ScpFBus.sys (C:\Windows\system32\drivers\ScpVBus.sys). In this case, though, you will have to use some grep-like tool -- one from this list, for example: https://www.slant.co/topics/5541/~gui-grep-implementations-for-windows to find which .inf file inside c:\windows \inf refers to ScpFBus.sys.

5 - After finding which .inf file is the right one, you can then uninstall that driver with this PowerShell command (replace the "oem71.inf" with the name you found:

`pnputil /delete-driver c:\windows\inf\oem71.inf /uninstall`

Done.
