### ISSUE TITLE
Unexpected app crash occured

### ISSUE THREAD

**Issue by keiintec** [djlastnight/KeyboardSplitterXbox#153]
Hello, I have a problem that I cannot solve, and it is that the app does not start, I have already installed the joystick drivers, I have installed dx 2013 etc etc and I cannot find a solution attached my splitter_log

[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/10688806/splitter_log.txt)

**Comment by djlastnight** [comment]
I believe you need to enable WMI on your system.

**Comment by keiintec** [comment]
thanks for the help, but I was able to solve it, in the end the only thing
that worked for me was to format the pc

**Comment by djlastnight** [comment]
Well, this will definitely work yes, because the WMI is enabled by default :)

**Comment by keiintec** [comment]
Awesome, thanks! :)
