### ISSUE TITLE
Keyboard Splitter Issues (Help me)

### ISSUE THREAD

**Issue by N0DD0N** [djlastnight/KeyboardSplitterXbox#156]
**When I open my keyboard splitter all it does is show a white window pop up for some seconds and then close back, I havent tried any interception method but just incase I will paste my log for you to see** 
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/10817303/splitter_log.txt)

**Comment by djlastnight** [comment]
Hi, do you have everything here https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites installed?
