### ISSUE TITLE
Mouse movement translating to right analog stick movement is choppy and awkward.

### ISSUE THREAD

**Issue by Conni128** [djlastnight/KeyboardSplitterXbox#157]
How would one make it so that it moves how a normal mouse would move?

**Comment by djlastnight** [comment]
Mouse support is kinda limited. You can just adjust the sensitivity at the settings. I never used the mouse ingame

**Comment by djlastnight** [comment]
Can you please try let say 50% axis with the mouse and say if it works as expected https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#custom-axes-range-0-100

**Comment by mrx-00** [comment]
Hi @djlastnight,

I have the same feeling. I didn't look into the implementation but I think it has something to do with the fact that you can assign the individual mouse directions to the joystick directions. At least the movement feels like there is only the input 1 and 0 in all directions.

If this is true, I would suggest to map the mouse movement as one event with a deltaX and deltaY value to the respective joystick axes.

```
joyStick.RightAxis.X = mouseEvent.DeltaX * someFactorX;
joyStick.RightAxis.Y = mouseEvent.DeltaY * someFactorY;
```

The values for `someFactorX` and `someFactorY` need to be figured out based on the delta range. Example: If the delta range is `[-1..1]` and the JoyStick range is `[-32768..32767]` you could use `32767` as factor.

This would allow a more fluent movement based on how much you move the mouse in both directions. Might be a good idea to make this configurable through the UI, in case the maximum joystick value requires too much or less mouse movement. Or respect the DPI settings of the mouse, this would need of course some experimentation as well.

**Comment by djlastnight** [comment]
Yep, exactly. Please try the link and say whether it works for you. For me it works good
