### ISSUE TITLE
Unexpected crash app

### ISSUE THREAD

**Issue by negyit** [djlastnight/KeyboardSplitterXbox#159]
How to solve this issue? Windows 11 laptop
I installed all the programs listed in the prerequisites
![image](https://user-images.githubusercontent.com/116903491/221941996-0535303e-f3ec-41e0-becb-24e156fa0d96.png)

**Comment by djlastnight** [comment]
Never tested on W11. Even the app says W10 :)))

**Comment by djlastnight** [comment]
@negyit make sure everything listed at [prerequisites](https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites) is installed
