### ISSUE TITLE
Can't open KeyboardSplitterXbox

### ISSUE THREAD

**Issue by xzarzyk** [djlastnight/KeyboardSplitterXbox#162]
![1](https://user-images.githubusercontent.com/128253241/226129318-ac6e4ced-5068-4cb1-ab0b-d371b50f625a.png)
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/11009292/splitter_log.txt)

**Comment by djlastnight** [comment]
Prerequisites not installed
