### ISSUE TITLE
Keyboard and Mouse broken after install

### ISSUE THREAD

**Issue by darkdenizen92** [djlastnight/KeyboardSplitterXbox#165]
I know this is a long shot but I installed this on Windows 11 using Parallels to install on my Macbook. After installing, the OS becomes completely unresponsive to all inputs - even externally connected USBs. 

Any ideas on a solution? It's a VM mostly for games so I can just reinstall Windows but barring that, I'd love a solution.

**Comment by SmashHits** [comment]
the program would take control of your mouse and keyboard (which its supposed to) but doing this somehow crashes your drivers sometimes (I think), at least that's what happened to me. although this is rare I think it should be put out what the solution is here, my mouse and keyboard started working again after **hard rebooting**. I don't know how to hard reboot on mac, but on windows you just hold the power button until your pc turns off

**Comment by djlastnight** [comment]
Wow, very very interesting case. I believe you are trying to do something I did not predict at all, so its normal to stall your system :)

**Comment by SmashHits** [comment]
Basically, yes
