### ISSUE TITLE
Key lag, delay

### ISSUE THREAD

**Issue by hoangtanak** [djlastnight/KeyboardSplitterXbox#169]
When using kbsplitter, the input is heavily delayed, even when i dont turn on input monitor, my computer is smooth to so the problem is from the keyboard splitter, how do i fix it?

**Comment by djlastnight** [comment]
You might wish to try to run the newest version, using CLI. https://github.com/djlastnight/KeyboardSplitterXbox#command-line-interface-cli

**Comment by steeddolan** [comment]
> You might wish to try to run the newest version, using CLI. https://github.com/djlastnight/KeyboardSplitterXbox#command-line-interface-cli

I am using the kbsplitter in a home-built arcade. 

I made bat files to trigger the games though the CLI. This is honestly the best approach if your using launch box as it preconfigures everything. The CLI opens when you select the game and closes when the game closes. This might be a good article in itself for DIY Arcades. 

However, with the CLI and the GUI I still get a massive delay. You can sit back and watch the game play without any new inputs. 

I am using Bluetooth keyboard to get around windows. The sticks and buttons use an Ultimarc I Pac 2.

**Comment by djlastnight** [comment]
Well, honestly idk where the problem might be. Can you please try to uninstall KS and install only the interception. You can find it at readme credits. If this app is causing the lag, we can't do much unfortunately
