### ISSUE TITLE
No input devices were detected

### ISSUE THREAD

**Issue by Galaxy1878** [djlastnight/KeyboardSplitterXbox#170]
i tried reinstalling every driver, i deleted SCP bus with wipe cleanerr but it didnt work
i tried your interception uninstaller but the program didnt work too.
i tried to use older versions it didnt work.

log:
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - Application started from C:\Users\*********\Downloads\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - User has write permissions: True
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - OS version: Windows 10 x64 build 19045 
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - Setting environment
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 17 MB] - Extracting native resources
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - Loading SplitterCore 2.0.0.3
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - Loading Interceptor 2.0.0.3
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - Loading VirtualXbox 2.0.0.3
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - Interception driver state: installed
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - ScpVBus driver state: installed
[Tue] 06 Jun, 2023 [00:56:43] [Mem: 20 MB] - Xbox accessories driver state: installed
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - Loading XinputWrapper 2.0.0.3
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - Trying to apply app [settings]
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - [settings] 'Mouse move dead zone' set to: 1
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - [settings] 'Display emulation information' set to: True
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - [settings] 'Starting virtual controller user index' set to: 1
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 41 MB] - Main window loaded
[Tue] 06 Jun, 2023 [00:56:44] [Mem: 42 MB] - No input devices were detected! Terminating application.

**Comment by caesar451** [comment]
I'm currently having the exact same problem. I'll attach the log
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12306638/splitter_log.txt)

**Comment by djlastnight** [comment]
It seems the keyboard (interception) driver does not work well on your system. Please try the newest version too.
