### ISSUE TITLE
Only running in background.

### ISSUE THREAD

**Issue by pacifiquem** [djlastnight/KeyboardSplitterXbox#171]
It is not showing interface but only run in background.

**Comment by djlastnight** [comment]
Interesting, can you provide some details?

**Comment by pacifiquem** [comment]
Sure @djlastnight,
I'm running keyboard splitter on LENOVO (16gb ram, 1tb SSD, g8). When I run it, it shows interface  for a short time and it disappear. When I go to task manager it's process is still there and running.

**Comment by djlastnight** [comment]
We had similar case and it was resolved by installing all the prerequisites. Chech the readme, there are links there. Hope this helps.

**Comment by pacifiquem** [comment]
Ok let me check it.

**Comment by pacifiquem** [comment]
working @djlastnight !!! Thank You !!!
