### ISSUE TITLE
Keybord splitter not working

### ISSUE THREAD

**Issue by Shockpl** [djlastnight/KeyboardSplitterXbox#172]
Hello i tying t open keybord splitter and showing up white window after 3 seconds crashing 
in logs nothing abaut error 
pls help me a soon as posible 
thx

**Comment by XxBhagwanxX** [comment]
@Shockpl did you get any solution for it??

**Comment by djlastnight** [comment]
Do you have all the prerequisites installed?

**Comment by djlastnight** [comment]
Genious
