### ISSUE TITLE
Getting Controller_Plug_In_Failed when trying to start

### ISSUE THREAD

**Issue by Human194** [djlastnight/KeyboardSplitterXbox#173]
I'm trying to use my keyboard and mouse as a controller so it works on a game that doesn't accept keyboard and mouse, but it shows the error Slot is invalidated - Controller_Plug_In_Failed. Can anyone help?

**Comment by djlastnight** [comment]
This often happens if another version of scpvbus is installed. If you have drivers for ps3 controller for example. The solution is to uninstall them from device manager and reinstall KS
