### ISSUE TITLE
Emulated key presses

### ISSUE THREAD

**Issue by Amorfide** [djlastnight/KeyboardSplitterXbox#174]
This works perfectly, if I use my physical keyboard. I want to use this, so that I can run a python script to press keys for me, so that it uses the controller input. For example, I map K to Axis Rx Max, when I press K it rotates my camera in game. If my python script presses K, it will type the letter K, but when in game, this program doesn't pick this up and hence the camera doesn't move. How can I do this?

**Comment by djlastnight** [comment]
Hi, you can't. KS uses low level keyboard drivers, which gets the input directly from the hardware. The key emulation is only possible at specific context, which is not exposed. If you know C# you can modify my source code to expose and API for key emulation. Anyways I believe this is not the proper way to achieve what you wish. Better expose an API to control the mounted virtual gamepad instead and control it directly from Phyton.
