### ISSUE TITLE
Keyboard Splitter Doesn't Run

### ISSUE THREAD

**Issue by sazzad-1456** [djlastnight/KeyboardSplitterXbox#176]
Unexpected crash error occurs repeatedly. I've attached the log file
It didn't open for once, I've tried the latest and older versions too it's the same in both cases
![Capture](https://github.com/djlastnight/KeyboardSplitterXbox/assets/141486065/289e906e-c1ec-4f17-8cb2-f8a06ab875ed)
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12266709/splitter_log.txt)

**Comment by sazzad-1456** [comment]
@djlastnight please help me

**Comment by djlastnight** [comment]
Make sure you have the Prerequisites installed https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites and it will run
