### ISSUE TITLE
Multi Direction Problem. 

### ISSUE THREAD

**Issue by feffom** [djlastnight/KeyboardSplitterXbox#178]
Hi, first of all thanks for the program, it works greatly, im just trying to find a workaround for multi direction wheel, thats not covered interely by the X/Y axis emulation. If you got any tip on the matter, i'll leave a print to ilustrate. 
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/54901162/a36edac0-9dee-4488-874c-ce5fb7a72993)

This red marked spots are not possible to reach using the AWSD, the cursor just skip it by a tiny little bit, is there any possible fix for it?

**Comment by djlastnight** [comment]
Hello, Can you go to the red spots, if you use a real 360 controller?

**Comment by miaw7** [comment]
Good day. Thanks for the tool. It looks really great, but there is same problem for me. 

It's Baldur's gate 3 context menu. Not possible to reach some menu items. Can't test this with real 360 controller but if people with real controllers don't have any complains, i assume they can reach it

In my case i can't access 2 icons: alchemy and sleep. I have marked it with 'X' on the picture. 
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/29707905/1acab9f5-6b26-4078-8923-534b00a921c8)

When i'm pressing Axis X min +  Axis Y max i can reach only one of 2 context menu items. Not enough angle to trigger another item i think. As yo can see, on the picture arrow shows the direction where my current Axis XY is located

And in this game it's not possible to navigate with other buttons. Only using axis XY. 

Would be good if you have some around cause really want to play this game on split screen

Thank you a lot mate!

**Comment by miaw7** [comment]
I was able to open solution in Visual Studio, redacted XboxAxisPosition.cs and i was able to reach desired buttons. But expectedly another buttons were not able to reach. So i assume that ideally would be good to have more Axis values, that can be configured. For example - add new button here 
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/29707905/e859ffdc-299a-4c27-a0ae-45f45d30aa92)

select Axis Y or Axis X and set desired angle you want to use. It can be a good adition that might fix a lot of such scenarios in the future but requires existing code changes

**Comment by miaw7** [comment]
Ok, basically the same i can probably do via splitter_presets..  didn't notice

**Comment by djlastnight** [comment]
Interesting case. This is a second request for axis custom mapping. It looks like I should bring live to this project again 😜

**Comment by djlastnight** [comment]
@miaw7 @feffom Can you please try this https://github.com/djlastnight/KeyboardSplitterXbox/tree/master#custom-axes-range-from--100-to-100
and tell whether it works for your games?

**Comment by miaw7** [comment]
@djlastnight feature you mentioned works, but in my case i found out that it's better just to modify existing axis so i don't need to set aditional buttons. But this approach you mentioned - could be also really useful in different scenarious. 

For Baldurs Gate 3 i have just changed values in splitter_presets.xml to
```
<axis id="1" value="-32768">Left</axis>
    <axis id="1" value="30767">Right</axis>
    <axis id="2" value="-32768">Down</axis>
    <axis id="2" value="30767">Up</axis>
```

original value here `<axis id="1" value="30767">Right</axis>` for example was 32767 but i changed to 30767 and now i'm able to reach all buttons in the circle 

looks like it's situational setting, not a bug as i think. Good to have such configuration, great tool, thank you

**Comment by djlastnight** [comment]
Nice, thanks for the feedback 🙂
