### ISSUE TITLE
I install Keyboard Splitter. Don't work keyboard and mouse. 

### ISSUE THREAD

**Issue by ArtyomTank** [djlastnight/KeyboardSplitterXbox#179]
I don't know what to do. After installing the program, the keyboard and mouse stopped working. 🙁

**Comment by ArtyomTank** [comment]
I fixed this "system recovery". I may have done something wrong during the installation. I'll try again later.

**Comment by djlastnight** [comment]
In theory you can fail your system if some of the prerequisites is not installed, but this is a rare case. Some users disables WMI service, which might be an issue too, but most probably some of the 3rd party drivers, which KS uses failed to properly install.
