### ISSUE TITLE
Slot is Invalidated

### ISSUE THREAD

**Issue by geetheboss** [djlastnight/KeyboardSplitterXbox#18]
whenever I load it up and press start, it always says my slot is invalidated: Controller plugin failed. is there any way I can fix this?

**Comment by djlastnight** [comment]
Hi, show me the log, please ;)

**Comment by YoUnG-MoNeY** [comment]
The is the error it shows for me. If it is to plug in Xbox controller then i dont have one, can it work without one?
[Fri] 05 Jul, 2019 [18:20:17] [Mem: 75 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!

**Comment by djlastnight** [comment]
Hey, I need the other lines. Why you skip them?

**Comment by YoUnG-MoNeY** [comment]
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Application started from C:\Users\User\Downloads\keyboardsplit\KeyboardSplitter.exe
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - User has write permissions: True
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - OS version: Windows 10 x64 build 17134 
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Setting environment
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 17 MB] - Loading interception 1.00
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 17 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading SplitterCore 2.2.0.0
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading Interceptor 2.2.0.0
[Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - Interception driver state: installed
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - ScpVBus driver state: installed
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - Xbox accessories driver state: installed
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Loading XinputWrapper 2.2.0.0
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Settings file not found
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Main window loaded
[Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - No input devices were detected! Terminating application.



This is what i get not, i get a message box saying "No input devices were detected"
How do i fix it?

**Comment by djlastnight** [comment]
Did you reboot your PC after the drivers installation process? If not reboot it not. If this is not the case - you have to clean-up the drivers. Please see issue #6, where I explain how to do that.

**Comment by djlastnight** [comment]
Any news on how this is going?

**Comment by YoUnG-MoNeY** [comment]
Sorry for not replying, it actually worked. Thank you much appreciated.

**Comment by chavezedem** [comment]
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Application started from C:\Users\User\Downloads\keyboardsplit\KeyboardSplitter.exe
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - User has write permissions: True
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - OS version: Windows 10 x64 build 17134
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 16 MB] - Setting environment
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 17 MB] - Loading interception 1.00
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 17 MB] - Loading VirtualXboxNative 2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading SplitterCore 2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading Interceptor 2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:28] [Mem: 22 MB] - Loading VirtualXbox 2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - Interception driver state: installed
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - ScpVBus driver state: installed
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 23 MB] - Xbox accessories driver state: installed
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Loading XinputWrapper 2.2.0.0
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Settings file not found
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - Main window loaded
> [Fri] 05 Jul, 2019 [21:17:29] [Mem: 39 MB] - No input devices were detected! Terminating application.
> 
> This is what i get now, i get a message box saying "No input devices were detected"
> How do i fix it?

I have a Similar issue, pls bellow is my log

[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - Application started from F:\Games\KEYBOARD Settings\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - User has write permissions: True
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - OS version: Windows 10 x64 build 18363 
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - Setting environment
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - Loading interception 1.00
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 25 MB] - Loading SplitterCore 2.2.0.0
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Thu] 19 Mar, 2020 [14:22:34] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Thu] 19 Mar, 2020 [14:22:36] [Mem: 26 MB] - Interception driver state: installed
[Thu] 19 Mar, 2020 [14:22:36] [Mem: 26 MB] - ScpVBus driver state: installed
[Thu] 19 Mar, 2020 [14:22:36] [Mem: 26 MB] - Xbox accessories driver state: installed
[Thu] 19 Mar, 2020 [14:22:37] [Mem: 39 MB] - Loading XinputWrapper 2.2.0.0
[Thu] 19 Mar, 2020 [14:22:37] [Mem: 39 MB] - Settings file not found
[Thu] 19 Mar, 2020 [14:22:37] [Mem: 39 MB] - Main window loaded
[Thu] 19 Mar, 2020 [14:22:37] [Mem: 40 MB] - No input devices were detected! Terminating application.

I've installed the Drivers and Restarted My PC but Issue still Persists

VC++ Installed
Xbox360 drivers installed

**Comment by chhabrapiyush393** [comment]
hello sir my keyboard splitter is not working i have done all the steps u have mentioned earlier.

**Comment by snehsiyar** [comment]
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 18 MB] - Application started from E:\Desktop\New folder\KeyboardSplitter.exe
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 18 MB] - User has write permissions: True
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362 
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 18 MB] - Setting environment
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 19 MB] - Loading interception 1.00
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Sun] 29 Mar, 2020 [01:50:35] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 25 MB] - Interception driver state: installed
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 25 MB] - ScpVBus driver state: installed
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 25 MB] - Xbox accessories driver state: installed
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 42 MB] - Loading XinputWrapper 2.2.0.0
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 42 MB] - Settings file not found
[Sun] 29 Mar, 2020 [01:50:36] [Mem: 42 MB] - Main window loaded
[Sun] 29 Mar, 2020 [01:50:37] [Mem: 43 MB] - Creating splitter with 2 slots 
[Sun] 29 Mar, 2020 [01:50:37] [Mem: 43 MB] - Creating input manager

This error is coming and splitter is not getting opened please help
