### ISSUE TITLE
My keyboard and mouse doesn't working 

### ISSUE THREAD

**Issue by Mackeryayyy** [djlastnight/KeyboardSplitterXbox#181]
After I reboot my pc, my keyboard and mouse stop working, a few key does work like fn+f2 or fn+f3. I really need a solution right now, btw I'm using Windows 11.

**Comment by djlastnight** [comment]
Never tested on W11. Probably keyboard interception driver is not working as it should

**Comment by Mackeryayyy** [comment]
> Never tested on W11. Probably keyboard interception driver is not working as it should

Is there any solution for it?

**Comment by djlastnight** [comment]
No idea 😞
