### ISSUE TITLE
Getting error that Unexpected app crash Occured 

### ISSUE THREAD

**Issue by smartrunnerRIR** [djlastnight/KeyboardSplitterXbox#183]
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/144583982/ec9cd3e7-be45-4019-a0bc-f0ffa6350343)
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12567692/splitter_log.txt)
i recently cleaned many files form the add or remove files but installed directx and microsoft 
DirectX 9.0c June
Vcredist 2013 x86
Microsoft's Xbox Accessories Driver (64 bit)
are installed 
Please help me

**Comment by djlastnight** [comment]
Check readme, prerequisites please, install them all

**Comment by Jagu2812** [comment]
not worked
