### ISSUE TITLE
Keyboard splitter not working 

### ISSUE THREAD

**Issue by rayyan-ray** [djlastnight/KeyboardSplitterXbox#184]
My keyboard splitter was working until today i installed scp for using ps3 controller as xbox i have got only one controller so i try to open it it doesnt, its showing controller doesn't plugged in i reinstalled rebooted, after that its showing no input devices detected, please help what should i do, I can't get the log because i deleted the whole file

**Comment by djlastnight** [comment]
Hey, KS is also using SCP , thats why you bricked it. You have to manually cleanup scp from device manager, uninstall ks drivers and then reboot. After this run KS, it will fix the mess for you, reboot again. Hope this helps :)

**Comment by rayyan-ray** [comment]
Thanks for the reply, but when i delete scp ps3 doesn't work as xbox I want them 2 to work at the same time is there trick to do that

**Comment by rayyan-ray** [comment]
Which are the drivers of Ks

**Comment by rayyan-ray** [comment]
![Uploading 16950232812551022058829.jpg…]()
Its showing like this

**Comment by rayyan-ray** [comment]
Log
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 17 MB] - Application started from D:\Fonts And Other Files\G\Keyboard.Splitter.2.2.0.0\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 17 MB] - User has write permissions: True
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - OS version: Windows 10 x64 build 22621 
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Setting environment
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Loading interception 1.00
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - Interception driver state: installed
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - ScpVBus driver state: installed
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - Xbox accessories driver state: installed
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Loading XinputWrapper 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Settings file not found
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Main window loaded
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - No input devices were detected! Terminating application.

**Comment by rayyan-ray** [comment]
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 17 MB] - Application started from D:\Fonts And Other Files\G\Keyboard.Splitter.2.2.0.0\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 17 MB] - User has write permissions: True
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - OS version: Windows 10 x64 build 22621 
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Setting environment
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Loading interception 1.00
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - Interception driver state: installed
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - ScpVBus driver state: installed
[Mon] 18 Sep, 2023 [11:24:16] [Mem: 21 MB] - Xbox accessories driver state: installed
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Loading XinputWrapper 2.2.0.0
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Settings file not found
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - Main window loaded
[Mon] 18 Sep, 2023 [11:24:17] [Mem: 41 MB] - No input devices were detected! Terminating application.
Log

**Comment by rayyan-ray** [comment]
Hi, the method you said works, but I want scp ps3 controller and KS work at the same time is there any method or any thing to do to make it work at the same time

**Comment by djlastnight** [comment]
Nope. They use different versions of the same bus.
