### ISSUE TITLE
selectable ls left stick % percentage for walk wiht keyboard in some games by emulating xbox series x controller

### ISSUE THREAD

**Issue by ACIXCIX0001** [djlastnight/KeyboardSplitterXbox#185]
just installed the software for this function which isn t there....
is there a way to edit the .ini files or something to create a custom percentage of the left joystick push like 10% 20% ?
this could allow to walk in games where no keyboard keybinding like Alt is implemented
would it be posible to implement a custom % percentage course progressions for the axis or just new present like 10 % 20 % "Axis Y 10%" | "Axis Y 20%" instead of just having the "Axis Y Max" ?
where is the the code in control of the ammount of distance the left joystick is emulated at in the repository files, the code that determine "Axis Y Max"  pushing to the max ?

![Screenshot 2023-09-22 143530](https://github.com/djlastnight/KeyboardSplitterXbox/assets/101479101/46b7c943-236f-4ff4-8e86-b52f30d6d4fe)

**Comment by djlastnight** [comment]
I guess this is 3rd request for similar stuff, so I should sit down and add support soon ;)
I am not sure if this will be an easy task, that's why I can't just point you where to modify the source code

**Comment by djlastnight** [comment]
Hey @ACIXCIX0001 actually the app already supports this, so there is no need to touch the source code at all.

Open splitter_presets.xml file and manually add the following line
`<axis id="1" value="-16384">None</axis>`
In case you do not have such file simply open the app, create a new preset, exit the app and save the presets when asked.

Open the app, choose the preset you just modified and your custom axis will appear at the preset UI as follows
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/19281127/3d092000-811b-4662-9cf2-1ea58b88d4be)

You have your custom axis created. You can use it as usual.

Here are the axis ids to use:
Left Stick X = 1
Left Stick Y = 2
Right Stick X = 4
Right Stick Y = 8

Values must be in range -32768 to 32767

**Comment by ACIXCIX0001** [comment]
2 years after, but,

thank for your answer
noted, will try asap.
