### ISSUE TITLE
PLS HELP ME ASAP!

### ISSUE THREAD

**Issue by V3NOM143** [djlastnight/KeyboardSplitterXbox#186]
Whenever I lauch the application it says unexpected app crash and check log. in log it says interception driver not found. i am trying to play naruto: ultimate ninja storm but I cant lauch keyboard splitter.

**Comment by V3NOM143** [comment]
here is the log :(
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12710461/splitter_log.txt)

**Comment by djlastnight** [comment]
Yep, it seems the driver is not installed. Check the readme how to uninstall drivers, especially the gui uninstaller
