### ISSUE TITLE
can you help me asap

### ISSUE THREAD

**Issue by shoma22** [djlastnight/KeyboardSplitterXbox#187]
when i open the application it doesn't start and shows unexpected app crash occured  and here is the splitter log 
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12873991/splitter_log.txt)

**Comment by djlastnight** [comment]
Hi, please make sure you have all the [prerequisites](https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites) installed.
Then ensure the WMI is running:
1. Start -> Run -> type wmimgmt.msc ( Alternatively, you can open WMI properties by going to Control Panel -> Administrative Tools -> Computer Management. In the left-hand pane, click Services & Applications -> WMI Control, right-click and select Properties.)
2. Right click WMI Control (Local) and click Properties
3. If WMI is working correctly, you will see Successfully connected window as shown below. 
https://kb.acronis.com/system/files/content/2019/04/62731/62731_02.png

**Comment by hilloneemo** [comment]
I have the same problem  also what if wmi control isnt working properly?
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/104214283/f82f3c42-2080-4d44-a8c7-9ca78e6fe2a9)

 @djlastnight

**Comment by djlastnight** [comment]
This is the first thing which appeared on google search, so you can try it https://keys.direct/blogs/blog/how-to-enable-wmi-windows-10
