### ISSUE TITLE
modified files message

### ISSUE THREAD

**Issue by mintharaN1fan** [djlastnight/KeyboardSplitterXbox#188]
When i try to run the exe, I get the message in the screenshot below. It generates the log below that. Then, when i try to run it again, it just opens and closes a window.
This was after I installed the drivers and rebooted my PC. I tried on 2 different computers but I get the same message. Just ti be clear, I just downloaded the code, didn't modify anything.

![Screenshot_1](https://github.com/djlastnight/KeyboardSplitterXbox/assets/147668506/1ad41cb8-3b01-4a27-b284-154fdd7468d5)

[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/12875583/splitter_log.txt)

**Comment by djlastnight** [comment]
Please unzip (extract) the downloaded archive to a folder, then start the app from this folder.
