### ISSUE TITLE
Issue on using keyboard splitter in Cemu Emulator (wii u emulator)

### ISSUE THREAD

**Issue by AnythingWS** [djlastnight/KeyboardSplitterXbox#189]
I am trying to play tekken tag tournament 2 in cemu emulator with your software but whenever I start the software and try to run the emulator there is absolutely no response in the emulation. In the input setting from cemu I did select the api as directinput and the controller as the xbox 360 one. But there is no response. Please help

**Comment by djlastnight** [comment]
Hi. Please try to use xinput, instead of dinput in case you have such an option.
