### ISSUE TITLE
proplem with using mouse 

### ISSUE THREAD

**Issue by hussinali087** [djlastnight/KeyboardSplitterXbox#191]
hello!

i played cod bo3 
controlling with keyboard is very good but when i use mouse very bad , lagging when i use mouse and its only 4 directions up,down,right,left , i can't move up-right like Northeast..etc 

hope u can help me and solve that problem

**Comment by djlastnight** [comment]
Hi, can you please find the [custom axis 0-100%](https://github.com/djlastnight/KeyboardSplitterXbox#custom-axes-range-from--100-to-100) at readme, here at github and try it. It should help you with the mouse movements

**Comment by hussinali087** [comment]
hello i didn't fix the problem, i do like what u tell me i want the red direction like direction in the pic so i do some Mathematical equations and i'm very bad in ^_^


![dirction](https://github.com/djlastnight/KeyboardSplitterXbox/assets/151701553/f75487e3-055d-4ee5-9b25-45f86c812eae)

after that i put it in preset folder but didn't work bc i don't know how to plural MouseMoveUp+MouseMoveRight...etc






![+](https://github.com/djlastnight/KeyboardSplitterXbox/assets/151701553/38958143-15e9-4b6e-a093-105684c43d81)
 
![7](https://github.com/djlastnight/KeyboardSplitterXbox/assets/151701553/3d8dd41f-20a7-4f6f-ba6f-3d3fbe4e2616)

 
 i hope u help me and thank u again to reply
