### ISSUE TITLE
Additive Custom Axes

### ISSUE THREAD

**Issue by OrionJAnd** [djlastnight/KeyboardSplitterXbox#193]
Is it possible to create a rule in the splitter_presets.xml file where certain key presses act as a value to be added/subtracted from the current axis value in that direction? In contrast to a value that the axis should be set to.

I am trying to have one button that inputs 100% on the y-axis of the left stick, and another that simply subtracts 15% from that same y-axis direction. It seems that I can only set the value rather than do any kind of arithmetic.

Thank you in advance.

**Comment by djlastnight** [comment]
Hey, sorry this is too advanced and you can not make it without source code modification
