### ISSUE TITLE
Mouse completely stops working

### ISSUE THREAD

**Issue by safinj34** [djlastnight/KeyboardSplitterXbox#194]
When i used this app for a while my mouse stped working suddenly.it worked on bios and safe mode but not on windows .i tried uninstalling the mouse drivers but nothing worked.i tried diffrent mouse.other mouse worked.but my expensive mouse didnt worked.after 2-3 restarts it works for a while then stopeed suddenly.

**Comment by djlastnight** [comment]
Probably the expensive one uses custom drivers. If you wish to use KS with that mouse, you should get rid of those drivers.

**Comment by safinj34** [comment]
Ok thanks.

**Comment by djlastnight** [comment]
Please let me known, if it works

**Comment by tharanakannangara** [comment]
my kayboad does not works can you help
