### ISSUE TITLE
Not working on windows 10 installed on mac

### ISSUE THREAD

**Issue by sifatoooo** [djlastnight/KeyboardSplitterXbox#2]
It says the application is already running, and pressing the ok button closes the application.

**Comment by djlastnight** [comment]
You are the second person of 17k, who complains about this. Please paste the game log contents here.

**Comment by sifatoooo** [comment]
Hi djlastnight,
Thanks a lot for this great software, it works great in my hp laptop. Somehow it doesn't on my mac. BTW, what to you mean by game log contents?

**Comment by djlastnight** [comment]
Omg. I meant splitter log contents (splitter_log.txt). I support one game, witch has log system too... that's why I made such typo ;)
Probably mac's mutex class is not working as it should. You can run the app using allow-multi-instance parameter, which may lead to another issues. Use on your risk. Good luck.

**Comment by sifatoooo** [comment]
Thanks for your comment. Below is the comments in log file - 
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 20 MB] - Application started from C:\Users\Sifat\Downloads\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 20 MB] - User has write permissions: True
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 21 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 21 MB] - OS version: Windows 10 x64 build 16299 
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 21 MB] - Setting environment
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 22 MB] - Extracting native resources
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 27 MB] - Loading SplitterCore 2.0.0.3
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 27 MB] - Loading Interceptor 2.0.0.3
[Tue] 21 Nov, 2017 [01:06:57] [Mem: 28 MB] - Loading VirtualXbox 2.0.0.3
[Tue] 21 Nov, 2017 [01:06:58] [Mem: 27 MB] - Interception driver state: not installed
[Tue] 21 Nov, 2017 [01:06:58] [Mem: 27 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 21 Nov, 2017 [01:06:58] [Mem: 27 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by sifatoooo** [comment]
I found the same issue for other persons in your youtube video, and installing vcredist13_x86 resolved it. I am closing the issue.

Thanks again for this awesome software! :)
