### ISSUE TITLE
Unexpected App Crash

### ISSUE THREAD

**Issue by rollnumber11** [djlastnight/KeyboardSplitterXbox#20]
I am using Keyboard Splitter 2.2.0, it was working perfectly but suddenly it says unexpected app crash. I tried to follow your instructions from Issue #6 but nothing happened. I'm attaching the log file as well.
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3625028/splitter_log.txt)

**Comment by rollnumber11** [comment]
After installing vcredist 2013, the application opens and closes immediately, I suspect it goes somewhere in the background but I'm not able to find it in Task Manager.

**Comment by djlastnight** [comment]
Sorry for the late reply. Can we connect via teamviewer to see what is wrong?

**Comment by jadeja789** [comment]
![vid](https://user-images.githubusercontent.com/41280343/70796698-eb813680-1dc8-11ea-9b38-49259e91abba.gif)
Hi...I am using Keyboard Splitter 2.2.0.3....whenever i try to play ashes cricket 2017 keeping the keyboard splitter started, it works for a few minutes and suddenly game either exits  or computer suddenly crashes....above gif contains footage after game have been stuck....you can see the game exiting itself after being stuck....also keyboard splitter is still working...i could almost play the game til 6-7 min.....in another scenario  it also crashes....have not included it.
please fix it.....

here is the log file..
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3960521/splitter_log.txt)


my system info is...
Lenovo Ideapad 330
intel i5 8th gen
nvidia geforce mx150
8gb/1tb
windows 10 v1909
os build: 18363.535

If you need more info please reply....

**Comment by djlastnight** [comment]
I never played that game, but the other users have input problems with it, because the game is not genuine.

**Comment by djlastnight** [comment]
> After installing vcredist 2013, the application opens and closes immediately, I suspect it goes somewhere in the background but I'm not able to find it in Task Manager.

Can you please try this fix https://youtu.be/ans2ArPO9V4

**Comment by Nhk989** [comment]
After windows update keyboard splitter showed unexpected apps crush but when i install  vcredist 2013 from then when i open keyboard its shows white page  and close automatically.

**Comment by Nhk989** [comment]
> 

> 

- [ ] [
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4938068/splitter_log.txt)
![we](https://user-images.githubusercontent.com/68429845/87791474-1ef6d880-c864-11ea-92d5-2c187fd51bb9.jpg)

](url)

**Comment by Nhk989** [comment]
[
![nh](https://user-images.githubusercontent.com/68429845/87791824-bf4cfd00-c864-11ea-985a-90fa56bd7806.jpg)

please suggest me any solution
](url)

**Comment by Nhk989** [comment]
KeyboardSplitter_1.2.0.2 run only in my pc but others can't run only show white screen

**Comment by djlastnight** [comment]
Let's continue discussion here #89

**Comment by OGXSTREET** [comment]
Hay man i was using the keyboard splitter for a few weeks, but suddenly for no reason it says that ![image](https://user-images.githubusercontent.com/128106906/225795338-3fe7b052-b72a-4dc0-b357-d320c99e4ea8.jpeg)

I have tried a lot of things on yt but nothing works.

**Comment by AukaatBhai** [comment]
keyboard splitter is crashing. it is not launching.
it is showing unexpected app crash.

**Comment by esan157** [comment]
i have some problema error soming splitter_log.txt 
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 17 MB] - Application started from C:\Users\karatoa\Downloads\gaming-keyboard-splitter_softradar-com\KeyboardSplitter.exe
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 17 MB] - User has write permissions: True
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 17 MB] - OS version: Windows 10 x64 build 19045 
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 17 MB] - Setting environment
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 18 MB] - Loading interception 1.00
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 21 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 16 Jan, 2024 [10:17:02] [Mem: 21 MB] - System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at Interceptor.InterceptionDriver.get_DriverState()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kannakamui7** [comment]
> Ei, cara, eu estava usando o divisor de teclado por algumas semanas, mas de repente, sem motivo, ele diz isso![imagem](https://user-images.githubusercontent.com/128106906/225795338-3fe7b052-b72a-4dc0-b357-d320c99e4ea8.jpeg)
> 
> Eu tentei muitas coisas no yt, mas nada funciona.

conseguiu?
