### ISSUE TITLE
How to get Keyboard Splitter to create four XB controllers from one keyboard

### ISSUE THREAD

**Issue by slvrshot** [djlastnight/KeyboardSplitterXbox#200]
I am trying to assign independent functions on my RecRoomMasters IPAC4....so that we can play four player games. Each of the 4 arcade sticks have unique keyboard functions assigned to them, but everytime try to assign say "Down" to Player 2s "Down" it erases Player 1's Down. 

Player 1s Arcade Stick function for down is mapped to down on the directional keypad.
Player 2s Arcade Stick function for down is mapped to "R"

When I try to change the Keyboard name...it says the key being pressed is assigned to Keyboard 1.

Please help! Thanks!

**Comment by djlastnight** [comment]
Hello, it is possible to use different sections of the same keyboard and create 4 gamepads, so I am really wondering what you made wrong. Probably a video would help?

**Comment by slvrshot** [comment]
I can record something when I return home but are there some additional settings I need to be using so that 1 keyboard is recognized as 4 controllers. Again assigning a key for one virtual gamepad will automatically  copy over to another gamepad.

**Comment by slvrshot** [comment]
@djlastnight 

As you can see 1 keyboard. Arcade sticks and buttons are mapped to different keys. Assigning a button for one gamepad automatically assigns the same button to other gamepad. I am unable to assign unique keys to the individual gamepads. 

https://github.com/djlastnight/KeyboardSplitterXbox/assets/16061438/58525ae3-8b3e-490e-b9a3-9c4cc1996756

**Comment by djlastnight** [comment]
Create a preset for each of the slots, please.
