### ISSUE TITLE
All keyboards plugged in stopped working

### ISSUE THREAD

**Issue by stefan2133451531** [djlastnight/KeyboardSplitterXbox#201]
I installed this program, played a game with it with a couple of friends and nothing went wrong at first, untill i shut the pc down and powered it on again now, no keyboards or mice work.

We used 2 mice, 2 keyboards and an xbox controller. The box to block keyboards was always checked.

Im looking for any advice or fixes to my issue, I know its probably tough but please if anyone has any idea tell me

Additional notes:at first the mouse worked when i booted the pc up again but stopped working, all the files to keyboard splitter were in the downloads folder and wouldnt open so i uninstalled them.

Edit : shortly after plugging in either mouse or keyboard they die, they have power for a while and stop, this has never been an issue before and i tried the keyboard and mice on this and another pc and the other worked just fine

**Comment by stefan2133451531** [comment]
nvm started working out of nowhere

**Comment by TheThreatner** [comment]
How you did it i have the same problem tell the solution!

**Comment by tharanakannangara** [comment]
> How you did it i have the same problem tell the solution!

me too my keyboad doesnt work but wen i restar my lap it works
