### ISSUE TITLE
Keyboard splitter not working

### ISSUE THREAD

**Issue by therealtechpatel** [djlastnight/KeyboardSplitterXbox#21]
When I open Keybaord splitter it shows this error
![Keyboard splitter error pop up](https://user-images.githubusercontent.com/49846868/65297774-2fdfaa80-dbbd-11e9-81f4-3e9062642d0d.png)
then it says this 
![Keyboard splitter error code](https://user-images.githubusercontent.com/49846868/65297752-15a5cc80-dbbd-11e9-8c13-3a033543e48d.png)
how do I fix this?

**Comment by djlastnight** [comment]
Probably you need to install vcredist 2013 x86
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

**Comment by djlastnight** [comment]
Also do this in order to clean up the interception driver. I had a problem with it after the currently most recent windows update.
