### ISSUE TITLE
error when installing :((

### ISSUE THREAD

**Issue by danionek** [djlastnight/KeyboardSplitterXbox#217]
![image](https://github.com/djlastnight/KeyboardSplitterXbox/assets/157060985/c78e3139-facb-48f1-8dbc-7a3d34c4a743)

logs:
[Mon] 06 May, 2024 [18:38:13] [Mem: 17 MB] - Application started from C:\Users\Daniel\Downloads\Keyboard.Splitter.2.3.0.0\KeyboardSplitter.exe
[Mon] 06 May, 2024 [18:38:13] [Mem: 17 MB] - User has write permissions: True
[Mon] 06 May, 2024 [18:38:13] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.3.0.0
[Mon] 06 May, 2024 [18:38:13] [Mem: 17 MB] - OS version: Windows 10 x64 build 22631 
[Mon] 06 May, 2024 [18:38:13] [Mem: 17 MB] - Setting environment
[Mon] 06 May, 2024 [18:38:13] [Mem: 18 MB] - Loading interception 1.00
[Mon] 06 May, 2024 [18:38:13] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 06 May, 2024 [18:38:13] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Mon] 06 May, 2024 [18:38:13] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Mon] 06 May, 2024 [18:38:13] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 06 May, 2024 [18:38:13] [Mem: 20 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Mon] 06 May, 2024 [18:38:13] [Mem: 21 MB] - System.Runtime.InteropServices.COMException (0x80070422): Nie można uruchomić określonej usługi, ponieważ jest ona wyłączona lub ponieważ nie są włączone skojarzone z nią urządzenia.

   w System.Management.ThreadDispatch.Start()
   w System.Management.ManagementScope.Initialize()
   w System.Management.ManagementObjectSearcher.Initialize()
   w System.Management.ManagementObjectSearcher.Get()
   w Interceptor.InterceptionDriver.get_DriverState()
   w KeyboardSplitter.App.ReportDriversState()
   w KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   w System.Windows.Application.OnStartup(StartupEventArgs e)
   w System.Windows.Application.<.ctor>b__1_0(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by danionek** [comment]
btw im using windows 11

**Comment by thaibinh0203** [comment]
how can you fix it
