### ISSUE TITLE
Keyboard splitter is not opening

### ISSUE THREAD

**Issue by RindMuhammad1** [djlastnight/KeyboardSplitterXbox#22]
When I open keyboard splitter it just show me white color for 5 seconds and then close. I have also did your interception method but does not work

**Comment by djlastnight** [comment]
Can you paste the log here

**Comment by baderanini** [comment]
I have the same problem and here are my logs:
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - Application started from C:\Users\bader y. anini\Desktop\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - User has write permissions: True
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - OS version: Windows 10 x64 build 18362 
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - Setting environment
[Fri] 01 Nov, 2019 [19:39:13] [Mem: 17 MB] - Extracting native resources
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 25 MB] - Interception driver state: installed
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 25 MB] - ScpVBus driver state: installed
[Fri] 01 Nov, 2019 [19:39:14] [Mem: 25 MB] - Xbox accessories driver state: installed
[Fri] 01 Nov, 2019 [19:39:16] [Mem: 41 MB] - Loading XinputWrapper 2.0.0.3
[Fri] 01 Nov, 2019 [19:39:16] [Mem: 41 MB] - Settings file not found
[Fri] 01 Nov, 2019 [19:39:16] [Mem: 41 MB] - Main window loaded
[Fri] 01 Nov, 2019 [19:39:16] [Mem: 42 MB] - Creating splitter with 1 slots 
[Fri] 01 Nov, 2019 [19:39:16] [Mem: 42 MB] - Creating input manager

**Comment by N0DD0N** [comment]
The same problem he has I have it too except I haven't tried the interception method (I don't know what it is -_-) Please help me

**Comment by N0DD0N** [comment]
Hello is anyone there, just incase here is my log
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/10807652/splitter_log.txt)

**Comment by N0DD0N** [comment]
HELP ME!!!!



please
