### ISSUE TITLE
i had the issue #6 then i restarted and now it cant find input devices

### ISSUE THREAD

**Issue by kohalikjuut** [djlastnight/KeyboardSplitterXbox#25]
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 18 MB] - Application started from C:\Users\Raiko\Desktop\controller\KeyboardSplitter.exe
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - User has write permissions: True
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - OS version: Windows 10 x64 build 18362 
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - Setting environment
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - Loading interception 1.00
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Sat] 16 Nov, 2019 [12:06:09] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Sat] 16 Nov, 2019 [12:06:10] [Mem: 25 MB] - Interception driver state: installed
[Sat] 16 Nov, 2019 [12:06:10] [Mem: 25 MB] - ScpVBus driver state: installed
[Sat] 16 Nov, 2019 [12:06:10] [Mem: 26 MB] - Xbox accessories driver state: installed
[Sat] 16 Nov, 2019 [12:06:10] [Mem: 50 MB] - Loading XinputWrapper 2.2.0.0
[Sat] 16 Nov, 2019 [12:06:10] [Mem: 50 MB] - Trying to apply app [settings]
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 50 MB] - [settings] 'Mouse move dead zone' set to: 1
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 50 MB] - [settings] 'Display emulation information' set to: True
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 50 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 51 MB] - [settings] 'Starting virtual controller user index' set to: 2
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 51 MB] - Main window loaded
[Sat] 16 Nov, 2019 [12:06:11] [Mem: 51 MB] - No input devices were detected! Terminating application.

**Comment by kirankrishna05** [comment]
Same here, when I open the keyboard splitter it shows 'no input devices detected' and it terminates what to do?

**Comment by djlastnight** [comment]
Ah that Windows 10 x64. I have to investigate what's wrong with it.

**Comment by djlastnight** [comment]
Please see this video https://youtu.be/ans2ArPO9V4
