### ISSUE TITLE
Slot is invalidated

### ISSUE THREAD

**Issue by SanjoJoseph** [djlastnight/KeyboardSplitterXbox#26]
when I click on start in keyboard splitter latest version it is showing slot is invalidated ,plug in controller failed.I am attaching my log file here.
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/3892157/splitter_log.txt)

**Comment by djlastnight** [comment]
Probably you have differwnt SCP Bus installed. Go to device manager and under system devices find it and uninstall it. Reboot, run KS - it should offer you to install drivers, do it and reboot again. Hope this helps.

**Comment by djlastnight** [comment]
See this link if you have such problem: https://github.com/djlastnight/KeyboardSplitterXbox#scp-virtual-bus-version-mismatch
