### ISSUE TITLE
keyboard splitter isnt opening.

### ISSUE THREAD

**Issue by gamesidk** [djlastnight/KeyboardSplitterXbox#28]
I followed all the steps correctly. (I am using Windows 10) But it will not open, it just shows me a white screen for 5-10 seconds and then closes. 

LOG: 
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - Application started from C:\Users\datdu\Downloads\Keyboard.Splitter.2.1.0.0\KeyboardSplitter.exe
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - User has write permissions: True
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.1.0.0
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - OS version: Windows 10 x64 build 18362 
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - Setting environment
[Thu] 19 Dec, 2019 [01:49:03] [Mem: 22 MB] - Extracting native resources
[Thu] 19 Dec, 2019 [01:49:04] [Mem: 29 MB] - Loading SplitterCore 2.1.0.0
[Thu] 19 Dec, 2019 [01:49:04] [Mem: 29 MB] - Loading Interceptor 2.1.0.0
[Thu] 19 Dec, 2019 [01:49:04] [Mem: 30 MB] - Loading VirtualXbox 2.1.0.0
[Thu] 19 Dec, 2019 [01:49:05] [Mem: 28 MB] - Interception driver state: installed
[Thu] 19 Dec, 2019 [01:49:05] [Mem: 28 MB] - ScpVBus driver state: installed
[Thu] 19 Dec, 2019 [01:49:05] [Mem: 28 MB] - Xbox accessories driver state: installed
[Thu] 19 Dec, 2019 [01:49:07] [Mem: 48 MB] - Loading XinputWrapper 2.1.0.0
[Thu] 19 Dec, 2019 [01:49:07] [Mem: 48 MB] - Settings file not found
[Thu] 19 Dec, 2019 [01:49:07] [Mem: 48 MB] - Main window loaded
[Thu] 19 Dec, 2019 [01:49:07] [Mem: 49 MB] - Creating splitter with 1 slots 
[Thu] 19 Dec, 2019 [01:49:07] [Mem: 49 MB] - Creating input manager

EDIT: It also freezes my mouse and keyboard until it closes itself.

**Comment by djlastnight** [comment]
Strange. Can you try to uninstall the interception driver.
Download this app https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true
then reboot. After reboot start Keyboard Splitter - it will ask you to install the missing drivers. Do it and reboot again.

**Comment by javeedshaik717** [comment]
Hey same problem. Still not working

**Comment by javeedshaik717** [comment]
And it goes off

**Comment by javeedshaik717** [comment]
![Uploading 15848913559265945780514288493332.jpg…]()

**Comment by Rushi-45** [comment]
I am having the same problem, I uninstall the inception then it asks to install something and then reboot. But again when I open keyboard splitter the same problem occurs.

**Comment by YashodeepDhas32** [comment]
Same problem here but no response from the uploader

[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4757329/splitter_log.txt)

**Comment by Prasad43** [comment]
Facing the same issue. App will not open, it just shows me a white screen for 5-10 seconds and then closes.Can you please assist

please note: I have followed the steps in https://github.com/djlastnight/KeyboardSplitterXbox/issues/28#issuecomment-569840146 

Log sheet:

[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application started from D:\KeyboardSplitter.exe
[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - User has write permissions: True
[Sat] 05 Sep, 2020 [15:27:05] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - OS version: Windows 10 x64 build 18362 
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Setting environment
[Sat] 05 Sep, 2020 [15:27:06] [Mem: 18 MB] - Extracting native resources
[Sat] 05 Sep, 2020 [15:27:09] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:10] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Interception driver state: installed
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - ScpVBus driver state: installed
[Sat] 05 Sep, 2020 [15:27:15] [Mem: 25 MB] - Xbox accessories driver state: installed
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Loading XinputWrapper 2.0.0.3
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Settings file not found
[Sat] 05 Sep, 2020 [15:27:21] [Mem: 36 MB] - Main window loaded

**Comment by MOURYAS2001** [comment]
hay guys I got a prob with its when I try to start its connect my keyboard to controller 2, not 1 help me pls

**Comment by djlastnight** [comment]
Let's discuss this on #89

**Comment by HZLYB** [comment]
No input devices were detected!Application will now close!   

显示这个报错怎么办呢!! 谢谢
