### ISSUE TITLE
unexpected app crash occurs

### ISSUE THREAD

**Issue by jeet270** [djlastnight/KeyboardSplitterXbox#29]
![image](https://user-images.githubusercontent.com/59075103/71226907-81eeb400-2303-11ea-8717-f32f1d0e30f3.png)

**Comment by djlastnight** [comment]
Install vcredist 2013 x86 first. Then run KS, it should install Interception driver.

**Comment by jeet270** [comment]
thank you sir

**Comment by djlastnight** [comment]
You are welcome. Please, let me know does it work.

**Comment by hdd45** [comment]
![image](https://user-images.githubusercontent.com/51121709/77829954-4efe5c80-714b-11ea-8c63-575a2a07e4b3.png)
similar app crash problem with this log

**Comment by hdd45** [comment]
![image](https://user-images.githubusercontent.com/51121709/77829997-7e14ce00-714b-11ea-8e07-1acaf6caee23.png)

**Comment by hdd45** [comment]
Thanks!
Fixed it myself.
Restarted Windows Management Instrumentation(wmi) with web help.

You have done an awesome job creating this software!!
Thank you so much.
