### ISSUE TITLE
Slot is Invalidated Controller_Plug_In_Failed

### ISSUE THREAD

**Issue by hosnavch** [djlastnight/KeyboardSplitterXbox#31]
I've seen your other solutions for this error and tried them all.
I was using ScpToolkit to connect my Dualshock 3 to my PC before so as you wrote on other issues, I thought that might be causing this problem.
-So I uninstalled ScpToolkit and restarted my pc.
-I've downloaded and installed every necessary drivers.
-I uninstalled Interception using CMD following your steps on youtube.
-I reinstalled the necessary parts and rebooted.
And still having this problem.
Here is my log txt:

**Comment by hosnavch** [comment]
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4004876/splitter_log.txt)

**Comment by djlastnight** [comment]
Yep, I bet the problem core resides at SCP virtual bus.
Can you please try the ScpToolkit Clean Wipe Utility?
See what I found on ScpToolkit's issues: "Go to Device Manager, and uninstall the drivers for PLAYSTATION3(R) Controller, XBOX 360 Controller, and make sure to select the delete check mark while uninstalling".
