### ISSUE TITLE
when playing cricket 19 ,some controls doesnt work properly

### ISSUE THREAD

**Issue by bukyapavankumar** [djlastnight/KeyboardSplitterXbox#35]
when playing cricket 19 ,the back shot for right hander doesnt work ,same for left hander but in opposite  direction.i dont know whats the reason for this misbehaviour.

**Comment by Adnan-Niloy** [comment]
> when playing cricket 19 ,the back shot for right hander doesnt work ,same for left hander but in opposite direction.i dont know whats the reason for this misbehaviour.

I am facing the same problem.

**Comment by bukyapavankumar** [comment]
suprisingly,it works when gaming with parsec (multiplayer).idk why this happens.but still when playing single player it doesnt work.

**Comment by vishalbalabhakthula** [comment]
Sat] 20 Jun, 2020 [19:35:06] [Mem: 18 MB] - Application started from C:\Users\light\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - User has write permissions: True
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - OS version: Windows 10 x64 build 18363 
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Setting environment
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Loading interception 1.00
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading SplitterCore 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading Interceptor 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading VirtualXbox 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - Interception driver state: not installed
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by vishalbalabhakthula** [comment]
how to install interception ???

**Comment by ambilal2525** [comment]
i am facing same issue, all the shots work fine but the mid-off shot for right handed batsman and mid on shot for left handed batsman doesnt work

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#keyboard-ghosting
Change the bindings.

**Comment by bukyapavankumar** [comment]
im using my laptop keyboard also changing binding doesnt solve this issue

**Comment by djlastnight** [comment]
Are you 100% sure there is no ghosting?

**Comment by bukyapavankumar** [comment]
> Are you 100% sure there is no ghosting?

yes 100% sure. i only have problem with this specific game.idk why it happens

**Comment by Adnan-Niloy** [comment]
> > Are you 100% sure there is no ghosting?
> 
> yes 100% sure. i only have problem with this specific game.idk why it happens. through parsec it works fine with the same game and keyboad splitter
> ![Screenshot (11)](https://user-images.githubusercontent.com/25202276/117319579-0f0abc80-aea9-11eb-892a-1636ca18ab5a.png)

Same goes for me....

**Comment by bukyapavankumar** [comment]
@djlastnight  can you look into this? demo version of this game is in steam .can you please check this issue

**Comment by djlastnight** [comment]
@bukyapavankumar give me a link here to test this game

**Comment by djlastnight** [comment]
Let's continue here #12
