### ISSUE TITLE
Mouse is very delayed

### ISSUE THREAD

**Issue by Dismade** [djlastnight/KeyboardSplitterXbox#36]
I love this program, thank you so much for it. The keyboard and every other button works fine, but the mouse has a strong delay. Not just when the program is started but all the time, just when I'm moving the cursor around. It only stops when I close the program. Is there any way to fix this?

**Comment by Dismade** [comment]
Coming back to say it only happens on versions above 1.2.0.2 (https://github.com/djlastnight/KeyboardSplitterXbox/releases/tag/1.2.0.2)

**Comment by Dismade** [comment]
Another update, I realized if I have the program open, then move my mouse away from the window the mouse is no longer delayed, BUT that only applies if the KeyboardSplitter program is the focus window of my PC. If I clicked another window the mouse is delayed once again meaning I still can't play the game with a normal mouse.

**Comment by djlastnight** [comment]
Yes, this is a known issue.
