### ISSUE TITLE
Keyboard splitter is not working

### ISSUE THREAD

**Issue by Avinash135** [djlastnight/KeyboardSplitterXbox#39]
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4363461/splitter_log.txt)
Please find the log attached for your reference. Please sir guide me how I can fix the issue.

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
