### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by rushishah07** [djlastnight/KeyboardSplitterXbox#42]
ive been trying to install keyboard splitter but log.txt shows this issue please help me out.
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4399208/splitter_log.txt)
here's the log.txt please read it and let me know how to solve the issue

**Comment by umerasghar** [comment]
how did you solve this?
