### ISSUE TITLE
Its Not Working, Can any one suggest me some help.

### ISSUE THREAD

**Issue by igeniousnick** [djlastnight/KeyboardSplitterXbox#43]
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 18 MB] - Application started from C:\Users\NIKHIL P SAMUEL\Desktop\KeyboardSplitter.exe
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 18 MB] - User has write permissions: True
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 19 MB] - OS version: Windows 10 x64 build 18362 
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 19 MB] - Setting environment
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 19 MB] - Loading interception 1.00
[Mon] 30 Mar, 2020 [12:46:02] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 25 MB] - Interception driver state: installed
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 26 MB] - ScpVBus driver state: installed
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 26 MB] - Xbox accessories driver state: installed
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 42 MB] - Loading XinputWrapper 2.2.0.0
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 42 MB] - Settings file not found
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 42 MB] - Main window loaded
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 42 MB] - Creating splitter with 4 slots 
[Mon] 30 Mar, 2020 [12:46:03] [Mem: 43 MB] - Creating input manager

**Comment by djlastnight** [comment]
Please see the existing issues, before posting new ones.
