### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Pavan0903** [djlastnight/KeyboardSplitterXbox#45]
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - Application started from C:\Users\Surya\Downloads\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - User has write permissions: True
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - OS version: Windows 10 x64 build 18363 
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - Setting environment
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 21 MB] - Extracting native resources
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 29 MB] - Loading SplitterCore 2.0.0.3
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 29 MB] - Loading Interceptor 2.0.0.3
[Sat] 04 Apr, 2020 [17:34:48] [Mem: 29 MB] - Loading VirtualXbox 2.0.0.3
[Sat] 04 Apr, 2020 [17:34:49] [Mem: 30 MB] - Interception driver state: installed
[Sat] 04 Apr, 2020 [17:34:49] [Mem: 30 MB] - ScpVBus driver state: installed
[Sat] 04 Apr, 2020 [17:34:49] [Mem: 30 MB] - Xbox accessories driver state: installed
[Sat] 04 Apr, 2020 [17:34:50] [Mem: 41 MB] - Loading XinputWrapper 2.0.0.3
[Sat] 04 Apr, 2020 [17:34:50] [Mem: 42 MB] - Settings file not found
[Sat] 04 Apr, 2020 [17:34:50] [Mem: 42 MB] - Main window loaded
[Sat] 04 Apr, 2020 [17:34:50] [Mem: 42 MB] - No input devices were detected! Terminating application.

This is what i am getting

**Comment by djlastnight** [comment]
Obsolete version
