### ISSUE TITLE
No input device detected error 

### ISSUE THREAD

**Issue by palakshah0221** [djlastnight/KeyboardSplitterXbox#47]
Hi 
Could you please help in solving the error i tried all the way which was provided in issue 6 but still it is not working for me. Trying multiple way to resolve error but still at starting point It would be great if i could run the app and play the game.
1. log file attached.
2. Error Message Screenshot.

Thank you in advance 

![error](https://user-images.githubusercontent.com/47940979/79201713-1d2d0b80-7e56-11ea-9098-c5d6a02c3c43.jpg)

[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/4473997/splitter_log.txt)

**Comment by djlastnight** [comment]
@palakshah0221, can you please confirm you installed all from here: https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites

**Comment by aditya-chaphekar** [comment]
@djlastnight i also have the same error. I have all the prerequiste installed .The program was working like charm but due to some reasons i had to uninstall the drivers so i unistalled it from the drivers-> uninstall. After that when i try to reinstall it dosent work

**Comment by djlastnight** [comment]
@aditya-chaphekar did you update your windows recently? Strange things happens recently and we could not understand what's the problem.

**Comment by aditya-chaphekar** [comment]
Yes I did Update my Windows. So after some digging I found out the driver was not unistalled correctly. So i researched more on the internet and came across this video of yours (probably) and after following the instructions to uninstall interception drivers it worked like charm again. 

Link to Video
https://youtu.be/ans2ArPO9V4

**Comment by djlastnight** [comment]
hehe, yes you found my video, ok closing 🗡️
