### ISSUE TITLE
please tell me how to fix this issue it was working just fine till yesterday but as soon as i installed fifa19 it started crashing

### ISSUE THREAD

**Issue by JodhveerSingh** [djlastnight/KeyboardSplitterXbox#52]
![splitter_log - Notepad 06-05-2020 17_03_29](https://user-images.githubusercontent.com/64902591/81172470-ed3bd880-8fbb-11ea-91cf-ec088ee39575.png)

Please help me its not working!!!!

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
