### ISSUE TITLE
Main KB disabled

### ISSUE THREAD

**Issue by LegzRwheelz** [djlastnight/KeyboardSplitterXbox#53]
So as soon as I start KB Splitter, my keyboard and mouse are disabled, I have to use my steam controller to navigate the app. I have clicked around the app, trying different settings to change this behavior. According to the app, I hve multiple keyboards on my system, which technically is not wrong. Counting my main, my steam controller and my rc6 remote. I would just like it to disable the steam controller when the app is launched.

**Comment by djlastnight** [comment]
This is not possible
