### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by abhiachee** [djlastnight/KeyboardSplitterXbox#54]
[Tue] 12 May, 2020 [01:52:35] [Mem: 12 MB] - Application started from C:\Users\admin\Downloads\KeyboardSplitter.exe
[Tue] 12 May, 2020 [01:52:35] [Mem: 12 MB] - User has write permissions: True
[Tue] 12 May, 2020 [01:52:35] [Mem: 12 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 12 May, 2020 [01:52:35] [Mem: 12 MB] - OS version: Windows 10 x64 build 17134 
[Tue] 12 May, 2020 [01:52:35] [Mem: 12 MB] - Setting environment
[Tue] 12 May, 2020 [01:52:35] [Mem: 13 MB] - Loading interception 1.00
[Tue] 12 May, 2020 [01:52:35] [Mem: 13 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 12 May, 2020 [01:52:36] [Mem: 17 MB] - Loading SplitterCore 2.2.0.0
[Tue] 12 May, 2020 [01:52:36] [Mem: 17 MB] - Loading Interceptor 2.2.0.0
[Tue] 12 May, 2020 [01:52:36] [Mem: 17 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 12 May, 2020 [01:52:40] [Mem: 17 MB] - Interception driver state: not installed
[Tue] 12 May, 2020 [01:52:40] [Mem: 18 MB] - ScpVBus driver state: installed
[Tue] 12 May, 2020 [01:52:40] [Mem: 18 MB] - Xbox accessories driver state: installed
[Tue] 12 May, 2020 [01:52:42] [Mem: 18 MB] - Built-in drivers are not installed, asking user to install them
[Tue] 12 May, 2020 [01:52:49] [Mem: 46 MB] - Installing interception driver
[Tue] 12 May, 2020 [01:52:51] [Mem: 47 MB] - Could not write to \system32\drivers
[Tue] 12 May, 2020 [01:52:51] [Mem: 47 MB] - Skipping virtual xbox bus (SCP) driver installation, because it is already installed
[Tue] 12 May, 2020 [01:52:52] [Mem: 47 MB] - Application exited with code: 0
[Tue] 12 May, 2020 [01:52:56] [Mem: 47 MB] - Installation Error: Interception driver reports it is not installed

Kindly help

**Comment by djlastnight** [comment]
All explained at the log. Try manually install interception https://github.com/oblitum/Interception#driver-installation
