### ISSUE TITLE
Keyboard spiltter not working.See Log

### ISSUE THREAD

**Issue by ghost** [djlastnight/KeyboardSplitterXbox#56]
[Wed] 13 May, 2020 [14:48:50] [Mem: 8 MB] - Application started from D:\Games\New folder\KeyboardSplitter.exe
[Wed] 13 May, 2020 [14:48:50] [Mem: 8 MB] - User has write permissions: True
[Wed] 13 May, 2020 [14:48:50] [Mem: 8 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Wed] 13 May, 2020 [14:48:50] [Mem: 8 MB] - OS version: Windows 10 x64 build 18362 
[Wed] 13 May, 2020 [14:48:50] [Mem: 8 MB] - Setting environment
[Wed] 13 May, 2020 [14:48:50] [Mem: 9 MB] - Loading interception 1.00
[Wed] 13 May, 2020 [14:48:50] [Mem: 9 MB] - Loading VirtualXboxNative 2.2.0.0
[Wed] 13 May, 2020 [14:48:53] [Mem: 12 MB] - Loading SplitterCore 2.2.0.0
[Wed] 13 May, 2020 [14:48:53] [Mem: 12 MB] - Loading Interceptor 2.2.0.0
[Wed] 13 May, 2020 [14:48:53] [Mem: 12 MB] - Loading VirtualXbox 2.2.0.0
[Wed] 13 May, 2020 [14:48:54] [Mem: 13 MB] - Interception driver state: installed
[Wed] 13 May, 2020 [14:48:54] [Mem: 13 MB] - ScpVBus driver state: installed
[Wed] 13 May, 2020 [14:48:54] [Mem: 13 MB] - Xbox accessories driver state: installed
[Wed] 13 May, 2020 [14:48:58] [Mem: 32 MB] - Loading XinputWrapper 2.2.0.0
[Wed] 13 May, 2020 [14:48:58] [Mem: 32 MB] - Settings file not found
[Wed] 13 May, 2020 [14:48:58] [Mem: 32 MB] - Main window loaded
[Wed] 13 May, 2020 [14:48:58] [Mem: 33 MB] - Creating splitter with 1 slots 
[Wed] 13 May, 2020 [14:48:58] [Mem: 33 MB] - Creating input manager

**Comment by soldier270** [comment]
Will it run in Windows10Pro

**Comment by deepak70007** [comment]
[Tue] 19 May, 2020 [06:30:14] [Mem: 25 MB] - Application started from C:\Users\Tiya\Downloads\KeyboardSplitter.exe
[Tue] 19 May, 2020 [06:30:14] [Mem: 25 MB] - User has write permissions: True
[Tue] 19 May, 2020 [06:30:14] [Mem: 25 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 19 May, 2020 [06:30:14] [Mem: 25 MB] - OS version: Windows 10 x64 build 18363 
[Tue] 19 May, 2020 [06:30:14] [Mem: 25 MB] - Setting environment
[Tue] 19 May, 2020 [06:30:14] [Mem: 26 MB] - Loading interception 1.00
[Tue] 19 May, 2020 [06:30:14] [Mem: 26 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 19 May, 2020 [06:30:14] [Mem: 33 MB] - Loading SplitterCore 2.2.0.0
[Tue] 19 May, 2020 [06:30:14] [Mem: 33 MB] - Loading Interceptor 2.2.0.0
[Tue] 19 May, 2020 [06:30:14] [Mem: 33 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 19 May, 2020 [06:30:15] [Mem: 30 MB] - Interception driver state: not installed
[Tue] 19 May, 2020 [06:30:15] [Mem: 30 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 19 May, 2020 [06:30:15] [Mem: 30 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs,

**Comment by deepak70007** [comment]
admin please Resolve this error

**Comment by ammarbhatka** [comment]
I thought the game download process would be hard but making run keyboard splitter is harder...its not even opening the apk ... do something

**Comment by deepak70007** [comment]
No answer to my question.I do not understand what you want to say in this
email.


*but i Resolve this problem and working properly keyboard splitter.*
