### ISSUE TITLE
not even getting installed read every single issue that has been raised for the past 1year not even one was helpful 

### ISSUE THREAD

**Issue by iaamdp** [djlastnight/KeyboardSplitterXbox#57]
its not getting installed every time it shows read .txt with an error
![Screenshot (6)](https://user-images.githubusercontent.com/65345044/81930414-2b617980-9606-11ea-9bae-0d3087488954.png)
![Screenshot (7)](https://user-images.githubusercontent.com/65345044/81930417-2c92a680-9606-11ea-927b-3a1b678ca333.png)

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
