### ISSUE TITLE
This thing lags and delay of press a keyboard on my computer  , I can't control for few seconds, i believe its blocked keyboard and mouse hotkey while playing games

### ISSUE THREAD

**Issue by skatefilter360** [djlastnight/KeyboardSplitterXbox#58]
Can you remove that hotkey  blockied  keyboard and mouse cuz i accidentally press LEFT/ RIGHT CTRL and get stuck in game , i cant press ALT+TAB key and move the mouse.

and the app is lagging my keypress can u fix this iusse?

**Comment by djlastnight** [comment]
You accidentally press it 5 times in a row? Closing this!
