### ISSUE TITLE
my keyboardsplitter is not working 

### ISSUE THREAD

**Issue by Muhtasim780** [djlastnight/KeyboardSplitterXbox#59]
my keyboard splitter isn't opening at all... installed and restarted well bt then no response.

here is my log

[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - Application started from D:\Games\Cricket 19\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - User has write permissions: True
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - OS version: Windows 10 x64 build 18363 
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - Setting environment
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 17 MB] - Extracting native resources
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 23 MB] - Loading SplitterCore 2.0.0.3
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 23 MB] - Loading Interceptor 2.0.0.3
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 23 MB] - Loading VirtualXbox 2.0.0.3
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 24 MB] - Interception driver state: installed
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 24 MB] - ScpVBus driver state: installed
[Sun] 07 Jun, 2020 [21:11:49] [Mem: 24 MB] - Xbox accessories driver state: installed
[Sun] 07 Jun, 2020 [21:11:50] [Mem: 41 MB] - Loading XinputWrapper 2.0.0.3
[Sun] 07 Jun, 2020 [21:11:50] [Mem: 41 MB] - Settings file not found
[Sun] 07 Jun, 2020 [21:11:50] [Mem: 41 MB] - Main window loaded
[Sun] 07 Jun, 2020 [21:11:50] [Mem: 42 MB] - Creating splitter with 1 slots 
[Sun] 07 Jun, 2020 [21:11:50] [Mem: 42 MB] - Creating input manager

**Comment by vishalbalabhakthula** [comment]
Sat] 20 Jun, 2020 [19:35:06] [Mem: 18 MB] - Application started from C:\Users\light\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - User has write permissions: True
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - OS version: Windows 10 x64 build 18363 
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Setting environment
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Loading interception 1.00
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading SplitterCore 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading Interceptor 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 26 MB] - Loading VirtualXbox 2.2.0.0
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - Interception driver state: not installed
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sat] 20 Jun, 2020 [19:35:06] [Mem: 27 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
