### ISSUE TITLE
Commandline API request

### ISSUE THREAD

**Issue by xMugSx** [djlastnight/KeyboardSplitterXbox#61]
it works great easiest tool to setup and works on all games and I dont even need a keyboard as I'm using an encoder (ultimarc) and I can setup 2 joysticks only request it will be to setup an autostart setup with a saved profile to be able to use it with a front end on an arcade machine not sure if that's  even possible?

**Comment by jarazix** [comment]
I'd like this feature too. I love the tool, but the manual startup means its a little less seamless for my front end. Still the best tool I have used and its small price to pay...but hey...doesn't hurt to ask.

**Comment by imotep33** [comment]
same as everyone, it's great and simple app. it just needs to be able to lanch it via a frontend with and argument. 
somthing like \keyboardsplitter.exe -[game]  and the game name could be the .exe file or the "argument" in the game profile

**Comment by djlastnight** [comment]
Guys, you can try the new version. It supports launching with a specific game https://github.com/djlastnight/KeyboardSplitterXbox#command-line-interface-cli
