### ISSUE TITLE
No input devices were detected! Terminating application.

### ISSUE THREAD

**Issue by neo0912** [djlastnight/KeyboardSplitterXbox#62]
i have this problem when i open your app.
here are the logs

[Sun] 28 Jun, 2020 [13:42:57] [Mem: 18 MB] - Application started from C:\Users\GG\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 18 MB] - User has write permissions: True
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 18 MB] - OS version: Windows 10 x64 build 18363 
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 18 MB] - Setting environment
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 19 MB] - Loading interception 1.00
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Sun] 28 Jun, 2020 [13:42:57] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 25 MB] - Interception driver state: installed
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 25 MB] - ScpVBus driver state: installed
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 25 MB] - Xbox accessories driver state: installed
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - Loading XinputWrapper 2.2.0.0
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - Trying to apply app [settings]
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - [settings] 'Mouse move dead zone' set to: 1
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - [settings] 'Display emulation information' set to: True
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - [settings] 'Starting virtual controller user index' set to: 1
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 65 MB] - Main window loaded
[Sun] 28 Jun, 2020 [13:42:58] [Mem: 66 MB] - No input devices were detected! Terminating application.

**Comment by djlastnight** [comment]
Here is the fix https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true
