### ISSUE TITLE
keyboard splitter xmin ymin not working together

### ISSUE THREAD

**Issue by ambilal2525** [djlastnight/KeyboardSplitterXbox#63]
hi i am facing an issue with these combinations, all of my axis work fine and even with the combination, eg up and right button work together fine, but down and left button never work together, if i use a combination of right and down it works fine, but the left and down button isnt working together

**Comment by SadmanFahad** [comment]
hi i am facing an issue with these combinations, all of my axis work fine and even with the combination, eg up and right button work together fine, but down and left button never work together, if i use a combination of right and down it works fine, but the left and down button isnt working together(2)

**Comment by cricketlover310** [comment]
very rubbish application....
I am not able to play ashes cricket 17 properly...
I am not able to play certain shots because x-min and y-min are not pressing together

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#keyboard-ghosting
