### ISSUE TITLE
keyboard splitter not working

### ISSUE THREAD

**Issue by PramukhNagol** [djlastnight/KeyboardSplitterXbox#65]
![Capture](https://user-images.githubusercontent.com/68010685/86913409-44853300-c13c-11ea-837a-a20812a460fe.PNG)
It is displaying like this today. Yesterday it worked Normally

**Comment by djlastnight** [comment]
I bet your windows were updated. [This app](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true) should do the trick for you.
