### ISSUE TITLE
KEYBOARD SPLITTER NOT WORKING

### ISSUE THREAD

**Issue by gurudatta2050** [djlastnight/KeyboardSplitterXbox#66]
@djlastnight
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/5032020/splitter_log.txt)
 Hello, i have followed ur last query and done as u said in that like uninstalling interception.exe and removing Scp Virtual Bus Driver and rebooted the system. yet when i try to install keyboard splitter, there's a white blank window opening and after a few seconds, its closing. Nothing's happening, pls do help me on this issue. ty

**Comment by djlastnight** [comment]
Can you please try using an older version of my app?

**Comment by rohanchaudha** [comment]
**i am getting below error when i start installation.** 
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/5450817/splitter_log.txt)
please help me tosolve

**Comment by djlastnight** [comment]
No response, closing. Probably https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
