### ISSUE TITLE
Mouse stops moving when running program (without starting the driver)

### ISSUE THREAD

**Issue by NULUSIOS** [djlastnight/KeyboardSplitterXbox#68]
I am not sure if this is normal behavior (and how to actually use the program if it is), or something is wrong.
When I start the program, without "starting" the driver, the mouse stops working.
Keyboard works ok. I moved around with the tab key. Selecting "none" for keyboard/mouse, changed nothing.
Block keyboard is ticked. Block mouse is unticked. Although I switched both on and off. No change, mouse remains frozen.
I press Escape and program quits and mouse control resumes.

Help?
Latest program version, Windows 10 Pro x64 fully patched.

**Comment by djlastnight** [comment]
I am reading the issues after a long delay and you are the second person, reporting such issue.
The last time I was active here, I discovered that W10 x64 updates are making interception driver go crazy.
I would recommend to reinstall it by using this [app](https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true)

**Comment by NULUSIOS** [comment]
Can I ask what is this?

**Comment by djlastnight** [comment]
Interception driver uninstaller. Run it, then reboot, then start KS - it should ask you to install the drivers. Reboot again and check whether this fix your problem

**Comment by FABCPY** [comment]
I want to ask you if you can help me with a problem.
Download and install keyboardSplitter 2.2.0.0 software from this page below.

https://www.softpedia.com/get/System/System-Miscellaneous/Gaming-Keyboard-Splitter.shtml#disqus_thread

After installing I asked to restart windows 10, and what happens is that it no longer recognizes my keyboard and mouse, I can do nothing within windows but turn the computer off and on with the physical button.
