### ISSUE TITLE
Keyboard splitter stopped working

### ISSUE THREAD

**Issue by ghost** [djlastnight/KeyboardSplitterXbox#71]
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 18 MB] - Application started from D:\Games\Keyboard.Splitter.2.2.0.0 (1)\KeyboardSplitter.exe
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 18 MB] - User has write permissions: True
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 18 MB] - OS version: Windows 10 x64 build 16299 
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 18 MB] - Setting environment
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 19 MB] - Loading interception 1.00
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 25 MB] - Interception driver state: installed
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 25 MB] - ScpVBus driver state: installed
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 25 MB] - Xbox accessories driver state: installed
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 36 MB] - Loading XinputWrapper 2.2.0.0
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 36 MB] - Settings file not found
[Wed] 28 Oct, 2020 [16:24:02] [Mem: 36 MB] - Main window loaded
[Wed] 28 Oct, 2020 [16:24:03] [Mem: 36 MB] - Creating splitter with 2 slots 
[Wed] 28 Oct, 2020 [16:24:03] [Mem: 37 MB] - Creating input manager

**Comment by PevDiePee** [comment]
Same problem

**Comment by djlastnight** [comment]
Too much very similar if not the same issues. Closing this. See https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
