### ISSUE TITLE
Some input problems

### ISSUE THREAD

**Issue by SadmanFahad** [djlastnight/KeyboardSplitterXbox#74]
Using version 2.2
In laptop playing fifa...internal keyboard working properly with that software but in external keyboard down and left together not working for moving but when i change the control is working...and some input like Q and F are delaying and sometimes not working....
Please fix this problem asap so we play in peace..
Thanks

**Comment by djlastnight** [comment]
Sounds like ghosting: https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#keyboard-ghosting
