### ISSUE TITLE
Keyboard Splitter is crashing. Asks everytime to install drivers

### ISSUE THREAD

**Issue by hemantkolate** [djlastnight/KeyboardSplitterXbox#75]
The keyboard splitter is not working on windows 10. Tried all the things mentioned but still won't work. No idea why it is happening. Everytime I run the .exe file it asks to install the drivers and run application again
@djlastnight Please tell what to do

**Comment by hemantkolate** [comment]
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 25 MB] - Application started from C:\Users\Hemant Kolate\Downloads\Keyboard.Splitter.2.2.0.0 (1)\KeyboardSplitter.exe
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 25 MB] - User has write permissions: True
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 25 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 25 MB] - OS version: Windows 10 x64 build 18362 
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 25 MB] - Setting environment
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 26 MB] - Loading interception 1.00
[Fri] 27 Nov, 2020 [10:29:09] [Mem: 26 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 33 MB] - Loading SplitterCore 2.2.0.0
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 33 MB] - Loading Interceptor 2.2.0.0
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 33 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 34 MB] - Interception driver state: installed
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 34 MB] - ScpVBus driver state: not installed
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 34 MB] - Xbox accessories driver state: installed
[Fri] 27 Nov, 2020 [10:29:10] [Mem: 35 MB] - Built-in drivers are not installed, asking user to install them
[Fri] 27 Nov, 2020 [10:29:15] [Mem: 51 MB] - Skipping interception driver installation, because it is already installed
[Fri] 27 Nov, 2020 [10:29:15] [Mem: 51 MB] - Installing virtual xbox bus (SCP) driver
[Fri] 27 Nov, 2020 [10:29:21] [Mem: 54 MB] - Output from ScpVBus installtion: Device node created. Install is complete when drivers are installed...
Updating drivers for Root\ScpVBus from C:\Users\Hemant Kolate\AppData\Local\Temp\VirtualXbox 2.2.0.0 resources\ScpVBus.inf.

[Fri] 27 Nov, 2020 [10:29:21] [Mem: 54 MB] - Application exited with code: 0
[Fri] 27 Nov, 2020 [10:29:43] [Mem: 54 MB] - Installtion OK. Closing the application, because it needs to be restarted.

**Comment by djlastnight** [comment]
Just reboot.

**Comment by Rahul93** [comment]
this happens in crossover mac and even if i reboot this happens again
