### ISSUE TITLE
Help Please doesn't recognize keyboard and mouse in windows 10

### ISSUE THREAD

**Issue by FABCPY** [djlastnight/KeyboardSplitterXbox#76]
I want to ask you if you can help me with a problem. 
Download and install keyboardSplitter 2.2.0.0 software from this page below. 

https://www.softpedia.com/get/System/System-Miscellaneous/Gaming-Keyboard-Splitter.shtml#disqus_thread

After installing I asked to restart windows 10, and what happens is that it no longer recognizes my keyboard and mouse, I can do nothing within windows but turn the computer off and on with the physical button.
Can you help me, please.

**Comment by djlastnight** [comment]
I already answered this in another issue. Do not install from 3rd party locations.
