### ISSUE TITLE
I am unable to run Keyboard Splitter - 

### ISSUE THREAD

**Issue by Abnv19** [djlastnight/KeyboardSplitterXbox#77]
![image](https://user-images.githubusercontent.com/43898238/101522585-72052f80-39ad-11eb-93ed-d48a4ab15b4c.png)
I am gettng this error and the emulator doesn't open...
Attaching splitter_log below
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/5660912/splitter_log.txt)
Pls help me @djlastnight

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
