### ISSUE TITLE
Getting Slot invalidated error!

### ISSUE THREAD

**Issue by wOOkie243** [djlastnight/KeyboardSplitterXbox#79]
I am unable to use Keyboard splitter as I am getting Slot Invalidated error. Below is the log file:

[Wed] 16 Dec, 2020 [17:00:47] [Mem: 18 MB] - Application started from C:\Users\anuj_\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - User has write permissions: True
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - OS version: Windows 10 x64 build 19041 
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - Setting environment
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - Loading interception 1.00
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Wed] 16 Dec, 2020 [17:00:47] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 25 MB] - Interception driver state: installed
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 26 MB] - ScpVBus driver state: installed
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 26 MB] - Xbox accessories driver state: installed
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 39 MB] - Loading XinputWrapper 2.2.0.0
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - Trying to apply app [settings]
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - [settings] 'Mouse move dead zone' set to: 1
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - [settings] 'Display emulation information' set to: True
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - [settings] 'Suggest input devices for new slots' set to: True
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - [settings] 'Starting virtual controller user index' set to: 1
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 40 MB] - Main window loaded
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 41 MB] - Creating splitter with 2 slots 
[Wed] 16 Dec, 2020 [17:00:48] [Mem: 41 MB] - Creating input manager
[Wed] 16 Dec, 2020 [17:00:50] [Mem: 55 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!
[Wed] 16 Dec, 2020 [17:01:04] [Mem: 62 MB] - Plug in Virtual Xbox 360 Controller #1 - Failed!

**Comment by NopeSiniping** [comment]
Exact the same issue.

**Comment by NopeSiniping** [comment]
Exactly the same problem.

**Comment by djlastnight** [comment]
#26
