### ISSUE TITLE
Keyboard splitter stops working after some time

### ISSUE THREAD

**Issue by Adit1313** [djlastnight/KeyboardSplitterXbox#8]
I just installed Keyboard Splitter 1.2 on my Windows 10 machine and at first, the software works as expected. However, after some amount of time, around 5 minutes in, it stops working.

**Comment by djlastnight** [comment]
It sounds like specific game issue to me. What's the game that you have tried? Can you confirm that this issue 'repeats' for let say 3 games?
Thanks for your feedback,
dj

**Comment by Adit1313** [comment]
I've been playing Don Bradman Cricket 17.
As for the issue repeating, I haven't tried other games yet.

**Comment by djlastnight** [comment]
There is no need to try another games. I confirm that this is game related issue. The 'demo' version of Don Bradman Cricket 17 stops the xinput gamepads after a given time.

I am closing the issue.
Thanks for your feedback.

**Comment by Adit1313** [comment]
Ah I see.
Thank you and great software!

**Comment by djlastnight** [comment]
You are welcome :)

**Comment by afroos001** [comment]
@djlastnight I am also facing same problem. please give me a solution

**Comment by IbrahimSidTechno** [comment]
> You are welcome :)



> There is no need to try another games. I confirm that this is game related issue. The 'demo' version of Don Bradman Cricket 17 stops the xinput gamepads after a given time.
> 
> I am closing the issue. Thanks for your feedback.

bro i am also facing this issue
