### ISSUE TITLE
Hanging issue of controls

### ISSUE THREAD

**Issue by alanjose2000** [djlastnight/KeyboardSplitterXbox#81]
HEY ,
I am facing a issue in keyboard splitter when playing cricket 19. When i simultaneously hold on multiple keys those controls goes on hanging or late action of those controls in the game.  Kindly please find a solution or its difficult to play the game.

**Comment by djlastnight** [comment]
You are probably facing the well known keyboard ghosting problem.
Due to this is not a KeyboardSplitter issue you have 2 options:
1. Buy an anti-ghosting keyboard
or
2. Change the preset bindings. Try which keys might be presses simultaneously here: https://drakeirving.github.io/MultiKeyDisplay/
