### ISSUE TITLE
Key Board Splitter is not getting started I don't know the problem. I am on a windows 10 laptop Please can anyone help me asap

### ISSUE THREAD

**Issue by Shyamgajn** [djlastnight/KeyboardSplitterXbox#82]
Here is the log for reference:
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 19 MB] - Application started from C:\Users\Admin\AppData\Local\Temp\Rar$EXa11020.36144\KeyboardSplitter.exe
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 19 MB] - User has write permissions: True
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 19 MB] - OS version: Windows 10 x64 build 18363 
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 19 MB] - Setting environment
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 20 MB] - Loading interception 1.00
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 20 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 25 MB] - Loading SplitterCore 2.2.0.0
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Mon] 11 Jan, 2021 [12:07:16] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 11 Jan, 2021 [12:07:17] [Mem: 26 MB] - Interception driver state: installed
[Mon] 11 Jan, 2021 [12:07:17] [Mem: 26 MB] - ScpVBus driver state: installed
[Mon] 11 Jan, 2021 [12:07:17] [Mem: 26 MB] - Xbox accessories driver state: installed
[Mon] 11 Jan, 2021 [12:07:18] [Mem: 56 MB] - Loading XinputWrapper 2.2.0.0
[Mon] 11 Jan, 2021 [12:07:18] [Mem: 56 MB] - Settings file not found
[Mon] 11 Jan, 2021 [12:07:18] [Mem: 56 MB] - Main window loaded
[Mon] 11 Jan, 2021 [12:07:18] [Mem: 56 MB] - Creating splitter with 2 slots 
[Mon] 11 Jan, 2021 [12:07:18] [Mem: 56 MB] - Creating input manager

**Comment by djlastnight** [comment]
Hey, unpack the rar first.
