### ISSUE TITLE
How do I custom keys?

### ISSUE THREAD

**Issue by kenny151345153** [djlastnight/KeyboardSplitterXbox#83]
.

**Comment by djlastnight** [comment]
You can read this at the app's file menu Help -> FAQ, but:
1. Create a preset or choose non-protected one ('default' preset is protected)
![image](https://user-images.githubusercontent.com/19281127/115228629-af778780-a11a-11eb-887b-d38a2d0de415.png)
2. Scroll down and click the Add custom function button
![image](https://user-images.githubusercontent.com/19281127/115228777-dd5ccc00-a11a-11eb-92d5-94fac7427066.png)
3. New mapping will appear, so set it for your needs.
![image](https://user-images.githubusercontent.com/19281127/115228910-05e4c600-a11b-11eb-84bf-1b4983968ddf.png)
4. Repeat 2-3 to add many custom functions.
