### ISSUE TITLE
Unable to auto-detect the keyboard

### ISSUE THREAD

**Issue by buntykumar720** [djlastnight/KeyboardSplitterXbox#84]
my keyboard splitter is not showing keyboard. always show is none waiting for keyboard input

-
![Screenshot (210)](https://user-images.githubusercontent.com/78783426/107323547-742e5c00-6acc-11eb-8155-5e236b1cc392.png)

**Comment by djlastnight** [comment]
@buntykumar720, can you manually choose it from the listbox?
Also when you expand the Input Device Monitor, and start typing - does it detect the keys?

**Comment by djlastnight** [comment]
no reply
