### ISSUE TITLE
Keyboard splitter not working especially for cricket 19

### ISSUE THREAD

**Issue by aztecwarchief** [djlastnight/KeyboardSplitterXbox#85]
I have been using keyboard splitter a lot. I have played a lot of games including Cricket 19 in it. But recently cricket 19 is not detecting any input when i switch on the splitter. i have tested with other games it works fine with them. i have tried reinstalling cricket 19 several times. tried it with original and cracked versions nothing seems to work. Any solution

**Comment by djlastnight** [comment]
Sounds like game (settings) related issue, so I can not really help.
