### ISSUE TITLE
I followed all your steps but cant open Keyboard SplitterXbox

### ISSUE THREAD

**Issue by pushkar1232** [djlastnight/KeyboardSplitterXbox#86]
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 18 MB] - Application started from C:\Users\1\Downloads\KeyboardSplitter.exe
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 18 MB] - User has write permissions: True
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 18 MB] - OS version: Windows 10 x64 build 18363 
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 18 MB] - Setting environment
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 19 MB] - Loading interception 1.00
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 25 MB] - Interception driver state: installed
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 25 MB] - ScpVBus driver state: installed
[Fri] 05 Mar, 2021 [13:48:44] [Mem: 25 MB] - Xbox accessories driver state: installed
[Fri] 05 Mar, 2021 [13:48:45] [Mem: 41 MB] - Loading XinputWrapper 2.2.0.0
[Fri] 05 Mar, 2021 [13:48:45] [Mem: 41 MB] - Settings file not found
[Fri] 05 Mar, 2021 [13:48:45] [Mem: 41 MB] - Main window loaded
[Fri] 05 Mar, 2021 [13:48:45] [Mem: 42 MB] - No input devices were detected! Terminating application.
 pls help

**Comment by djlastnight** [comment]
If you wish we could establish a team viewer session, so I can examine what's wrong.
