### ISSUE TITLE
Possible to emulate Xbox One or Series X/S controllers?

### ISSUE THREAD

**Issue by Cortana-117** [djlastnight/KeyboardSplitterXbox#87]
Hi,
is it possible to emulate Xbox one or Xbox Series X/S controllers?
I want to use it on PC (without physical controller) with Xbox xCloud and it only supports at least Xbox one controller.

**Comment by djlastnight** [comment]
Yes, it is possible, but this requres huge api changes - 1/2 of the app should be rewritten. I simply do not have so much free time to do it.

**Comment by Cortana-117** [comment]
Oh, didn't know it'd need that big of a change, well thank you for the response, hopefully someone else will do it or fork this :)
