### ISSUE TITLE
Keyboard splitter is not working!

### ISSUE THREAD

**Issue by pranavrajvansh** [djlastnight/KeyboardSplitterXbox#88]
It is showing "Try reset" keyboard splitter.
![keyboard](https://user-images.githubusercontent.com/64404220/113484039-f8490280-94c3-11eb-8324-e7fe3b9c7c62.PNG)

Please solve my issue!

**Comment by djlastnight** [comment]
Restart the pc - if the problem persists, probably you have another virtual joystick drivers installed, so they 'fight' each other.
