### ISSUE TITLE
White screen on open, then closes automatically

### ISSUE THREAD

**Issue by ZekeLandon** [djlastnight/KeyboardSplitterXbox#89]
Hey @djlastnight

I followed all the steps mentioned. Installed the necessary drivers. After restart, when I invoke the splitter application, **I see white screen for 5 seconds and then it closes automatically**. Could you help me here?

Splitter logs:
```
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 17 MB] - Application started from F:\Games\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 17 MB] - User has write permissions: True
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 17 MB] - OS version: Windows 10 x64 build 18363 
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 18 MB] - Setting environment
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 18 MB] - Loading interception 1.00
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Tue] 06 Apr, 2021 [13:04:15] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 21 MB] - Interception driver state: installed
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 21 MB] - ScpVBus driver state: installed
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 21 MB] - Xbox accessories driver state: installed
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 41 MB] - Loading XinputWrapper 2.2.0.0
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 41 MB] - Settings file not found
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 41 MB] - Main window loaded
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 41 MB] - Creating splitter with 1 slots 
[Tue] 06 Apr, 2021 [13:04:16] [Mem: 42 MB] - Creating input manager
```

**Comment by djlastnight** [comment]
Hey @ZekeLandon,
can you please confirm you have all this installed https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites

**Comment by iamspd2** [comment]
@djlastnight facing the same issue, with same log. Have made sure of all the prerequisites. Also tried Scp virtual bus and interception fixes as mentioned in another issue. Same result.

**Comment by djlastnight** [comment]
Oh, really, interesting. Did you update your windows recently. I suspect the interception driver goes crazy after win update.

**Comment by iamspd2** [comment]
Update: I could fix it after installing Microsoft's Xbox Accessories Driver. I had skipped this prerequisite step since it didn't mention Windows 10 which I'm using. It probably wasn't in mine. Try to research on it, if it doesn't come installed in every system, then you may have to update the prerequisite section for all OS versions.

**Comment by Hydraknight** [comment]
> 
> 
> Update: I could fix it after installing Microsoft's Xbox Accessories Driver. I had skipped this prerequisite step since it didn't mention Windows 10 which I'm using. It probably wasn't in mine. Try to research on it, if it doesn't come installed in every system, then you may have to update the prerequisite section for all OS versions.

Thank you sooo soo much, it worked!

**Comment by djlastnight** [comment]
@iamspd2 It is really strange, because MS said we won't need this driver anymore on W10. Thank you for finding and sharing the solution! I will update the section.

**Comment by tr2s0002** [comment]
I was able to solve this problem by installing the Direct X pack
