### ISSUE TITLE
i keep getting this error

### ISSUE THREAD

**Issue by Nardokrazy2x** [djlastnight/KeyboardSplitterXbox#9]
Solt is invalidated Controller_plug_in_failed

**Comment by djlastnight** [comment]
Hi,
would you attach (or paste) the log file here.
Thanks.

**Comment by djlastnight** [comment]
Probably the user has different (no matter newer or older) version of SCP VBus driver previously installed.
This issue is has been resolved months ago, but the fix will be available for the next release.

Since I have no feedback, I am closing the issue.

**Comment by djlastnight** [comment]
Please uninstall your current "Scp Virtual Bus Driver".
1. Open Device Manager -> System Devices
2. Right click on "Scp Virtual Bus Driver" and uninstall it (check the 'Delete the driver software for this device' checkbox).
3. Reboot your PC
4. Start Keyboard Splitter - it will ask you to install the driver(s). Do it and reboot your PC again.

This should fix the issue.

**Comment by Nardokrazy2x** [comment]
okay trying now

**Comment by djlastnight** [comment]
Nice, I am closing the current issue, since it is resolved. 

Please create new issue and explain your current problem better.

Thanks for your feedback,
dj
