### ISSUE TITLE
How to completely uninstall?

### ISSUE THREAD

**Issue by xkriya** [djlastnight/KeyboardSplitterXbox#93]
Fixed an issue I had with a controller and now I'm trying to completely uninstall keyboard splitter. How do I go about uninstalling all the drivers ?

**Comment by djlastnight** [comment]
if the app is still installed it is easy. Just go to its file menu and choose 'Drivers' -> 'Uninstall Built-in Drivers' option.
Reboot the pc, delete the following files
![image](https://user-images.githubusercontent.com/19281127/116377990-614d3d00-a81a-11eb-8458-0f17afd1d6ed.png)
and that's it.
