### ISSUE TITLE
How to use with SCPToolKit because im also using a DS3 controller?

### ISSUE THREAD

**Issue by thu2468** [djlastnight/KeyboardSplitterXbox#95]
How to use both software because keyboard splitter not working after install

**Comment by djlastnight** [comment]
Sorry this is possible only when you use the same scp virtual bus versions. Probabaly KS uses obsolete one. If you wish I will check the version for you.

**Comment by thu2468** [comment]
Ok thanks if u can check if there a way

**Comment by djlastnight** [comment]
![image](https://user-images.githubusercontent.com/19281127/119385656-1d414100-bccf-11eb-81bf-7e9f5ae1b2e8.png)
22.52.24.182

![image](https://user-images.githubusercontent.com/19281127/119386171-d0aa3580-bccf-11eb-94c3-ead9c2446026.png)
1.7.1.2

KS uses this repos https://github.com/djlastnight/KeyboardSplitterXbox#credits-original-authors-projects if this helps.
