### ISSUE TITLE
Mouse died after reboot

### ISSUE THREAD

**Issue by uz1mane** [djlastnight/KeyboardSplitterXbox#96]
I just installed your piece of software, clicked install required drivers and then rebooted, after the reboot my mouse cursor disappeared and i cant use my mouse right now (logitech g102), however the side buttons of my mouse are recognised and logitech g hub can see the mouse, but i still cant move the cursor using it. Other mouse (default logitech office mouse) is working fine. Any ideas how can i fix this before i reinstall windows?

**Comment by djlastnight** [comment]
It is really strange. I am sorry to hear that. Does this mouse uses additional drivers/software?
There is no need to reinstall windows. Connect your working mouse and open KS. Go to drivers menu and uninstall the drivers. Reboot and you will be fine.

**Comment by uz1mane** [comment]
Hi again, sorry for late answer. Yes my mouse used logitech driver software called "Logitech G Hub", i did uninstall all drivers in KS 
menu and rebooted but it didnt help, the sensor of the mouse still didnt work, however the side buttons did work. Soo i needed my computer really bad next day and i just reinstalled my windows :)

**Comment by Juna786** [comment]
why is it everytime i choose unsubscribe from this thread, it never works !!! i've been gettin notifications for the past 5 years !!!
